import { Fragment, jsx, jsxs } from "react/jsx-runtime";
import { useCallback, useEffect, useState } from "react";
import { DollarSign, CheckCircle, Clock, FileText, Plus, Upload, X, MessageCircle, Link2 } from "lucide-react";
import { Button } from "./Button";
import { formatLKR, formatRawLKR } from "../utils";
import { isCounselorEquivalentAccountRole } from "../roles";
import { useExchangeRates } from "../useExchangeRates";
import { getPaymentAccounts, uploadInvoicePaymentProof, getInvoicesByStudentId, resendInvoiceWhatsapp } from "../authApi";
import { toAbsoluteAssetUrl } from "../apiConfig";
import { COMPANY_NAME } from "../companyConfig";
import { MAX_UPLOAD_BYTES, MAX_UPLOAD_LABEL } from "../uploadLimits";
import {
  invoiceInvoicedAmount,
  invoiceApprovedPaid,
  invoiceBalanceDue,
  isInvoiceFullyPaid,
  evidenceDisplayAmount,
  evidencePaymentKind,
  evidencePaymentKindLabel,
  evidencePaymentKindClass,
  isFullPaymentReceiptAmount
} from "../invoicePaymentHelpers";
const PAYMENT_NOT_REFUNDABLE_NOTICE = "Payment is not refundable.";
const escapeInvoiceSvgText = (value) => String(value || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const generateInvoiceImageDataUrl = async ({ invoice, student, paymentAccount }) => {
  try {
    const amount = `${invoice.currency} ${Number(invoice.amount || 0).toLocaleString()}`;
    const studentName = escapeInvoiceSvgText(student?.name || "Student");
    const description = escapeInvoiceSvgText(invoice.description || "");
    const dueDate = escapeInvoiceSvgText(invoice.dueDate || "-");
    const issuedDate = escapeInvoiceSvgText(invoice.issueDate || "-");
    const invoiceId = escapeInvoiceSvgText(invoice.id || "");
    const payLines = paymentAccount
      ? [
          escapeInvoiceSvgText(paymentAccount.bankName || ""),
          escapeInvoiceSvgText(`${paymentAccount.accountName || ""} · ${paymentAccount.accountNumber || ""}`)
        ].filter(Boolean)
      : [];
    const svgHeight = (payLines.length ? 760 : 680) + 36;
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${svgHeight}" viewBox="0 0 1200 ${svgHeight}">
      <defs>
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="#eef2ff" />
          <stop offset="100%" stop-color="#f8fafc" />
        </linearGradient>
      </defs>
      <rect x="0" y="0" width="1200" height="${svgHeight}" fill="url(#bg)" />
      <rect x="40" y="40" width="1120" height="${svgHeight - 80}" rx="24" fill="#ffffff" stroke="#e2e8f0" />
      <text x="88" y="190" font-family="Arial, sans-serif" font-size="42" font-weight="700" fill="#1e293b">${escapeInvoiceSvgText(`${COMPANY_NAME} Invoice`)}</text>
      <text x="88" y="238" font-family="Arial, sans-serif" font-size="24" fill="#475569">Invoice ID: ${invoiceId}</text>
      <text x="88" y="290" font-family="Arial, sans-serif" font-size="22" fill="#64748b">Student</text>
      <text x="88" y="328" font-family="Arial, sans-serif" font-size="30" font-weight="600" fill="#0f172a">${studentName}</text>
      <text x="88" y="390" font-family="Arial, sans-serif" font-size="22" fill="#64748b">Description</text>
      <text x="88" y="428" font-family="Arial, sans-serif" font-size="28" fill="#0f172a">${description}</text>
      <text x="88" y="490" font-family="Arial, sans-serif" font-size="22" fill="#64748b">Issue Date</text>
      <text x="88" y="528" font-family="Arial, sans-serif" font-size="28" fill="#0f172a">${issuedDate}</text>
      <text x="88" y="570" font-family="Arial, sans-serif" font-size="22" fill="#64748b">Due Date</text>
      <text x="88" y="608" font-family="Arial, sans-serif" font-size="28" fill="#0f172a">${dueDate}</text>
      <rect x="760" y="240" width="340" height="220" rx="20" fill="#eef2ff" stroke="#c7d2fe" />
      <text x="790" y="310" font-family="Arial, sans-serif" font-size="22" fill="#4338ca">Total Amount</text>
      <text x="790" y="380" font-family="Arial, sans-serif" font-size="46" font-weight="700" fill="#312e81">${escapeInvoiceSvgText(amount)}</text>
      ${payLines.length ? `<text x="88" y="650" font-family="Arial, sans-serif" font-size="20" fill="#64748b">Pay to</text>
      <text x="88" y="688" font-family="Arial, sans-serif" font-size="24" fill="#0f172a">${payLines[0] || ""}</text>
      <text x="88" y="724" font-family="Arial, sans-serif" font-size="22" fill="#334155">${payLines[1] || ""}</text>` : ""}
      <text x="88" y="${svgHeight - 96}" font-family="Arial, sans-serif" font-size="18" font-weight="600" fill="#b45309">${escapeInvoiceSvgText(PAYMENT_NOT_REFUNDABLE_NOTICE)}</text>
      <text x="760" y="${svgHeight - 60}" font-family="Arial, sans-serif" font-size="20" fill="#64748b">Generated by ${escapeInvoiceSvgText(COMPANY_NAME)}</text>
    </svg>`;
    const encodedSvg = btoa(unescape(encodeURIComponent(svg)));
    const image = await new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => reject(new Error("invoice_image_render_failed"));
      img.src = `data:image/svg+xml;base64,${encodedSvg}`;
    });
    const canvas = document.createElement("canvas");
    canvas.width = 1200;
    canvas.height = svgHeight;
    const context = canvas.getContext("2d");
    if (!context) return "";
    context.fillStyle = "#ffffff";
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.drawImage(image, 0, 0, canvas.width, canvas.height);
    const logo = await new Promise((resolve) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => resolve(null);
      img.src = "/assets/company-full-logo.png";
    });
    if (logo) {
      const logoMaxWidth = 360;
      const logoHeight = 66;
      context.drawImage(logo, 88, 72, logoMaxWidth, logoHeight);
    }
    return canvas.toDataURL("image/png");
  } catch {
    return "";
  }
};
const INVOICE_ATTACHMENT_TYPES = new Set([
  "application/pdf",
  "image/png",
  "image/jpeg",
  "image/jpg",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
]);

function invoiceProofUrl(inv) {
  const raw = String(inv?.paymentProofUrl || "").trim();
  return raw ? toAbsoluteAssetUrl(raw) || raw : "";
}

function evidenceProofUrl(evidence) {
  const raw = String(evidence?.url || "").trim();
  return raw ? toAbsoluteAssetUrl(raw) || raw : "";
}

function hasRejectedPaymentEvidence(inv) {
  return Boolean(String(inv?.paymentRejectionReason || "").trim());
}

function collectInvoiceEvidenceItems(inv) {
  const items = [];
  const history = Array.isArray(inv?.paymentProofHistory) ? inv.paymentProofHistory : [];
  for (const entry of history) {
    const url = String(entry?.url || "").trim();
    const claimed = Number(entry?.claimedAmount);
    const approved = Number(entry?.approvedAmount);
    const hasAmount = (Number.isFinite(claimed) && claimed > 0) || (Number.isFinite(approved) && approved > 0);
    if (!url && !hasAmount) continue;
    items.push({
      url,
      name: String(entry?.name || "Payment evidence").trim(),
      uploadedAt: String(entry?.uploadedAt || "").trim(),
      outcome: String(entry?.outcome || (entry?.rejectionReason ? "rejected" : "superseded")).trim(),
      rejectionReason: String(entry?.rejectionReason || "").trim(),
      claimedAmount: entry?.claimedAmount,
      approvedAmount: entry?.approvedAmount,
      balanceDueAtUpload: entry?.balanceDueAtUpload,
      paidBeforeUpload: entry?.paidBeforeUpload,
      isCurrent: false
    });
  }
  const currentUrl = String(inv?.paymentProofUrl || "").trim();
  const status = String(inv?.status || "").trim();
  if (currentUrl) {
    let outcome = "pending";
    if (status === "Paid" && isInvoiceFullyPaid(inv)) outcome = "approved";
    else if (status === "Verifying") outcome = "pending";
    else if (hasRejectedPaymentEvidence(inv)) outcome = "rejected";
    items.push({
      url: currentUrl,
      name: String(inv?.paymentProofName || "Payment evidence").trim(),
      uploadedAt: String(inv?.paymentProofUploadedAt || inv?.updatedAt || inv?.issueDate || "").trim(),
      outcome,
      rejectionReason: String(inv?.paymentRejectionReason || "").trim(),
      claimedAmount: inv?.paymentProofClaimedAmount,
      balanceDueAtUpload: inv?.paymentProofBalanceDue,
      paidBeforeUpload: inv?.paymentProofPaidBefore,
      isCurrent: true
    });
  } else if (status === "Verifying") {
    const claimed = Number(inv?.paymentProofClaimedAmount);
    if (Number.isFinite(claimed) && claimed > 0) {
      items.push({
        url: "",
        name: String(inv?.paymentMethod || "").trim() === "Cash" ? "Cash payment" : "Payment evidence",
        uploadedAt: String(inv?.paymentProofUploadedAt || inv?.updatedAt || inv?.issueDate || "").trim(),
        outcome: "pending",
        rejectionReason: String(inv?.paymentRejectionReason || "").trim(),
        claimedAmount: inv?.paymentProofClaimedAmount,
        balanceDueAtUpload: inv?.paymentProofBalanceDue,
        paidBeforeUpload: inv?.paymentProofPaidBefore,
        isCurrent: true
      });
    }
  }
  return items;
}

function buildPaymentTableRows(invoices) {
  const rows = [];
  for (const inv of invoices) {
    const evidences = collectInvoiceEvidenceItems(inv);
    if (evidences.length === 0 && invoiceApprovedPaid(inv) > 0) {
      evidences.push({
        url: String(inv?.paymentProofUrl || "").trim(),
        name: String(inv?.paymentProofName || "Payment").trim(),
        uploadedAt: String(inv?.paidAmountRecordedAt || inv?.updatedAt || inv?.issueDate || "").trim(),
        outcome: "approved",
        rejectionReason: "",
        approvedAmount: invoiceApprovedPaid(inv),
        claimedAmount: inv?.paymentProofClaimedAmount,
        isCurrent: false
      });
    }
    evidences.forEach((evidence, idx) => {
      const outcome = String(evidence?.outcome || "").trim();
      if (outcome === "superseded") return;
      if (outcome !== "approved" && outcome !== "pending" && outcome !== "rejected") return;
      rows.push({
        invoice: inv,
        evidence,
        rowKey: `inv-${inv.id}-ev-${idx}-${evidence.uploadedAt || idx}`
      });
    });
  }
  return rows;
}

function isImageProof(url, name) {
  const hint = `${String(name || "")} ${String(url || "")}`.toLowerCase();
  if (hint.includes("data:image/")) return true;
  return /\.(png|jpe?g|gif|webp|bmp)$/i.test(hint.split("?")[0]);
}

function isPdfProof(url, name) {
  const hint = `${String(name || "")} ${String(url || "")}`.toLowerCase();
  return hint.includes("application/pdf") || /\.pdf$/i.test(hint.split("?")[0]);
}

function invoiceLedgerAmount(inv) {
  return invoiceInvoicedAmount(inv);
}

function formatPaymentTableDate(inv, evidence) {
  const raw = String(
    evidence?.uploadedAt ||
    inv?.paidAmountRecordedAt ||
    inv?.updatedAt ||
    inv?.issueDate ||
    ""
  ).trim();
  if (!raw) return "—";
  const datePart = raw.includes("T") ? raw.split("T")[0] : raw.slice(0, 10);
  return datePart || "—";
}

function getPaymentApprovalLabel(inv, evidence) {
  if (evidence) return getEvidenceApprovalLabel(evidence, inv);
  const status = String(inv?.status || "").trim();
  if (status === "Paid") return "Approved";
  if (status === "Partially Paid") return "Partially paid";
  if (status === "Verifying") return "Not approved";
  return "Pending";
}

function getEvidenceApprovalLabel(evidence, inv) {
  if (!evidence) return getPaymentApprovalLabel(inv);
  const outcome = String(evidence.outcome || "").trim();
  if (outcome === "approved") return "Approved";
  if (outcome === "rejected") return "Rejected";
  if (outcome === "pending" || String(inv?.status || "").trim() === "Verifying") return "Not approved";
  return "Pending";
}

function getPaymentApprovalClass(label) {
  if (label === "Approved") return "bg-emerald-50 text-emerald-700 border-emerald-200";
  if (label === "Partially paid") return "bg-violet-50 text-violet-700 border-violet-200";
  if (label === "Rejected") return "bg-rose-50 text-rose-700 border-rose-200";
  if (label === "Not approved") return "bg-blue-50 text-blue-700 border-blue-200";
  return "bg-amber-50 text-amber-700 border-amber-200";
}

const FinanceModule = ({ student, userRole, paymentAccounts = [], onCreateInvoice, onUpdateInvoice, onNotify, openCreateInvoice, counselorCanAcceptPayments = false }) => {
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [newAmount, setNewAmount] = useState("");
  const [newDesc, setNewDesc] = useState("");
  const [newCurrency, setNewCurrency] = useState("LKR");
  const [newDueDate, setNewDueDate] = useState("");
  const [newAttachmentLink, setNewAttachmentLink] = useState("");
  const [newAttachmentFile, setNewAttachmentFile] = useState(null);
  const [newPaymentAccountId, setNewPaymentAccountId] = useState("");
  const [resolvedPaymentAccounts, setResolvedPaymentAccounts] = useState(
    Array.isArray(paymentAccounts) ? paymentAccounts : []
  );
  const [createError, setCreateError] = useState("");
  const [isCreatingInvoice, setIsCreatingInvoice] = useState(false);
  const { rates: exchangeRates, updatedAt: rateUpdatedAt, live: ratesLive } = useExchangeRates();

  const [studentInvoices, setStudentInvoices] = useState([]);
  const [invoicesLoading, setInvoicesLoading] = useState(true);

  const loadStudentInvoices = useCallback(async () => {
    const sid = String(student?.id || "").trim();
    if (!sid) { setStudentInvoices([]); setInvoicesLoading(false); return; }
    setInvoicesLoading(true);
    const result = await getInvoicesByStudentId(sid);
    if (result.ok) setStudentInvoices(result.data);
    setInvoicesLoading(false);
  }, [student?.id]);

  useEffect(() => { loadStudentInvoices(); }, [loadStudentInvoices]);

  useEffect(() => {
    setResolvedPaymentAccounts(Array.isArray(paymentAccounts) ? paymentAccounts : []);
  }, [paymentAccounts]);

  const refreshPaymentAccounts = () => {
    return getPaymentAccounts().then((result) => {
      if (result.ok && Array.isArray(result.data)) {
        setResolvedPaymentAccounts(result.data);
      }
      return result;
    });
  };

  useEffect(() => {
    if (!onCreateInvoice) return;
    let cancelled = false;
    refreshPaymentAccounts().then(() => {
      if (cancelled) return;
    });
    return () => {
      cancelled = true;
    };
  }, [onCreateInvoice]);

  useEffect(() => {
    if (!isCreateOpen || !onCreateInvoice) return;
    refreshPaymentAccounts();
  }, [isCreateOpen, onCreateInvoice]);
  const totalPaid = studentInvoices.reduce(
    (acc, inv) => acc + invoiceApprovedPaid(inv) * (exchangeRates[inv.currency] || 1),
    0
  );
  const totalPending = studentInvoices.reduce(
    (acc, inv) => acc + invoiceBalanceDue(inv) * (exchangeRates[inv.currency] || 1),
    0
  );
  const resetCreateForm = () => {
    setNewAmount("");
    setNewDesc("");
    setNewDueDate("");
    setNewAttachmentLink("");
    setNewAttachmentFile(null);
    setNewPaymentAccountId("");
    setCreateError("");
  };

  const handleCreateSubmit = async (e) => {
    e.preventDefault();
    if (!onCreateInvoice) return;
    setCreateError("");
    const linkTrimmed = String(newAttachmentLink || "").trim();
    if (linkTrimmed && !/^https?:\/\//i.test(linkTrimmed)) {
      setCreateError("Reference link must start with http:// or https://");
      return;
    }
    if (newAttachmentFile) {
      if (newAttachmentFile.type && !INVOICE_ATTACHMENT_TYPES.has(newAttachmentFile.type)) {
        setCreateError("Unsupported attachment. Use PDF, JPG, PNG, DOC, or DOCX.");
        return;
      }
      if (newAttachmentFile.size > MAX_UPLOAD_BYTES) {
        setCreateError(`Attachment must be under ${MAX_UPLOAD_LABEL}.`);
        return;
      }
    }
    setIsCreatingInvoice(true);
    setIsCreateOpen(false);
    onNotify?.(
      "Invoice generation started",
      "The invoice popup is closed. Generation is running in the background and you will get an update in about 2-3 minutes.",
      "info",
      student?.id ? { studentId: student.id, view: "finance" } : null,
      7e3
    );
    const newInv = {
      id: `INV-${Date.now()}`,
      studentId: student.id,
      amount: parseFloat(newAmount),
      currency: newCurrency,
      description: newDesc,
      issueDate: (/* @__PURE__ */ new Date()).toISOString().split("T")[0],
      dueDate: newDueDate,
      status: "Pending"
    };
    const selectedAccount = resolvedPaymentAccounts.find((a) => String(a.id) === String(newPaymentAccountId));
    let invoiceAttachmentDataUrl;
    if (newAttachmentFile) {
      invoiceAttachmentDataUrl = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result || ""));
        reader.onerror = () => reject(new Error("read_error"));
        reader.readAsDataURL(newAttachmentFile);
      }).catch(() => "");
      if (!invoiceAttachmentDataUrl) {
        setCreateError("Unable to read attachment file.");
        setIsCreatingInvoice(false);
        return;
      }
    }
    const invoiceImageDataUrl = await generateInvoiceImageDataUrl({ invoice: newInv, student, paymentAccount: selectedAccount });
    const result = await onCreateInvoice({
      ...newInv,
      attachmentLink: linkTrimmed || void 0,
      paymentAccountId: newPaymentAccountId || void 0,
      invoiceAttachmentDataUrl: invoiceAttachmentDataUrl || void 0,
      invoiceAttachmentName: newAttachmentFile?.name,
      receiptImageDataUrl: invoiceImageDataUrl || void 0,
      receiptImageName: `${newInv.id}.png`
    });
    setIsCreatingInvoice(false);
    if (!result?.ok) {
      setCreateError(result?.error || "Failed to create invoice.");
      setIsCreateOpen(true);
      return;
    }
    resetCreateForm();
    onNotify?.(
      "Invoice generated",
      `Invoice ${result?.data?.id || newInv.id} is ready. We will keep you updated if any further processing is needed.`,
      "success",
      student?.id ? { studentId: student.id, view: "finance" } : null,
      7e3
    );
    loadStudentInvoices();
  };
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState(null);
  const [isDetailsModalOpen, setIsDetailsModalOpen] = useState(false);
  const [detailsInvoice, setDetailsInvoice] = useState(null);
  const [paymentMethod, setPaymentMethod] = useState("card");
  const [paymentProofFile, setPaymentProofFile] = useState(null);
  const [paymentClaimedAmount, setPaymentClaimedAmount] = useState("");
  const [paymentError, setPaymentError] = useState("");
  const [isSubmittingPayment, setIsSubmittingPayment] = useState(false);
  const [rejectModal, setRejectModal] = useState({ open: false, invoice: null, reason: "", error: "" });
  const [evidenceModal, setEvidenceModal] = useState({ open: false, invoice: null, evidence: null, paidAmount: "", error: "", saving: false });
  const [isRejecting, setIsRejecting] = useState(false);
  const [resendingInvoiceId, setResendingInvoiceId] = useState("");
  const [whatsappNotification, setWhatsappNotification] = useState({ show: false, message: "" });
  const showWhatsappNotification = (message) => {
    setWhatsappNotification({ show: true, message });
    setTimeout(() => setWhatsappNotification({ show: false, message: "" }), 4e3);
  };
  const showInvoiceWhatsappResult = (result, decisionLabel) => {
    const ws = result?.invoiceWhatsappNotification?.whatsapp;
    if (ws?.status === "sent") {
      showWhatsappNotification(
        `Invoice payment evidence was ${decisionLabel}. WhatsApp sent to the student from the counselor's linked account.`
      );
    } else if (ws?.status === "failed" || ws?.status === "skipped") {
      const detail = ws?.reason ? ` ${ws.reason}` : "";
      showWhatsappNotification(
        `Invoice payment evidence was ${decisionLabel}. WhatsApp was not sent.${detail}`
      );
    }
  };
  const handlePayClick = (invoice) => {
    setSelectedInvoice(invoice);
    setIsPaymentModalOpen(true);
    setPaymentMethod(canUploadEvidence ? "upload" : "card");
    setPaymentProofFile(null);
    setPaymentClaimedAmount("");
    setPaymentError("");
  };
  const handleOpenDetails = (invoice) => {
    setDetailsInvoice(invoice);
    setIsDetailsModalOpen(true);
  };
  const handlePaymentSubmit = async () => {
    if (!onUpdateInvoice || !selectedInvoice) return;
    setPaymentError("");
    setIsSubmittingPayment(true);
    if (canUploadEvidence && paymentMethod === "card") {
      setPaymentError("Choose Bank Transfer or Cash and upload proof for verification.");
      setIsSubmittingPayment(false);
      return;
    }
    if (paymentMethod === "card") {
      const result = await onUpdateInvoice({
        ...selectedInvoice,
        status: "Paid",
        paymentMethod: "Credit Card",
        generatedReceiptUrl: `REC-${selectedInvoice.id}.pdf`
      });
      if (!result?.ok) {
        setPaymentError(result?.error || "Failed to complete payment.");
        setIsSubmittingPayment(false);
        return;
      }
    } else {
      const balanceDue = invoiceBalanceDue(selectedInvoice);
      const claimedParsed = parseFloat(String(paymentClaimedAmount || "").trim());
      const isCashPayment = paymentMethod === "cash";
      if (!Number.isFinite(claimedParsed) || claimedParsed <= 0) {
        setPaymentError(isCashPayment ? "Enter the cash amount paid." : "Enter the amount shown on this receipt.");
        setIsSubmittingPayment(false);
        return;
      }
      if (claimedParsed > balanceDue + 0.009) {
        setPaymentError(`Amount cannot exceed the outstanding balance (${balanceDue.toLocaleString()}).`);
        setIsSubmittingPayment(false);
        return;
      }
      if (!isCashPayment && !paymentProofFile) {
        setPaymentError("Please upload payment proof.");
        setIsSubmittingPayment(false);
        return;
      }
      let dataUrl = "";
      let proofFileName = "";
      if (paymentProofFile) {
        const proofAllowedTypes = new Set([
          "application/pdf",
          "image/png",
          "image/jpeg",
          "image/jpg",
          "application/msword",
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        ]);
        if (paymentProofFile.type && !proofAllowedTypes.has(paymentProofFile.type)) {
          setPaymentError("Unsupported format. Use PDF, JPG, PNG, DOC, or DOCX.");
          setIsSubmittingPayment(false);
          return;
        }
        if (paymentProofFile.size > MAX_UPLOAD_BYTES) {
          setPaymentError(`Proof file must be under ${MAX_UPLOAD_LABEL}.`);
          setIsSubmittingPayment(false);
          return;
        }
        dataUrl = await new Promise((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = () => resolve(String(reader.result || ""));
          reader.onerror = () => reject(new Error("read_error"));
          reader.readAsDataURL(paymentProofFile);
        }).catch(() => "");
        if (!dataUrl) {
          setPaymentError("Unable to read payment proof file.");
          setIsSubmittingPayment(false);
          return;
        }
        proofFileName = paymentProofFile.name;
      }
      const uploadResult = await uploadInvoicePaymentProof(
        selectedInvoice.id,
        dataUrl || null,
        proofFileName,
        {
          claimedAmount: claimedParsed,
          paymentMethod: isCashPayment ? "Cash" : "Bank Transfer"
        }
      );
      if (!uploadResult.ok) {
        setPaymentError(uploadResult.error || "Failed to submit payment.");
        setIsSubmittingPayment(false);
        return;
      }
      const updateResult = await onUpdateInvoice(uploadResult.data);
      if (!updateResult?.ok) {
        setPaymentError(updateResult?.error || "Payment submitted but status update failed.");
        setIsSubmittingPayment(false);
        return;
      }
      const paymentLabel = isCashPayment && !paymentProofFile ? "Cash payment" : "payment evidence";
      onNotify?.(
        isCashPayment && !paymentProofFile ? "Cash payment submitted" : "Evidence uploaded",
        `${isFullPaymentReceiptAmount(claimedParsed, balanceDue) ? "Full" : "Partial"} ${paymentLabel} (${selectedInvoice.currency} ${claimedParsed.toLocaleString()}) for invoice ${selectedInvoice.id} was submitted for review.`,
        "success"
      );
    }
    setIsSubmittingPayment(false);
    setIsPaymentModalOpen(false);
    setSelectedInvoice(null);
    setPaymentProofFile(null);
    setPaymentClaimedAmount("");
    loadStudentInvoices();
  };
  const handleApprove = async (invoice, paidAmount) => {
    if (!onUpdateInvoice) return { ok: false, error: "Unable to update invoice." };
    const parsed = typeof paidAmount === "number" ? paidAmount : parseFloat(String(paidAmount || "").trim());
    if (!Number.isFinite(parsed) || parsed <= 0) {
      return { ok: false, error: "Enter a valid amount greater than zero before approving." };
    }
    const balanceDue = invoiceBalanceDue(invoice);
    if (parsed > balanceDue + 0.009) {
      return {
        ok: false,
        error: `Receipt amount cannot exceed the outstanding balance (${balanceDue.toLocaleString()}).`,
      };
    }
    const result = await onUpdateInvoice({
      ...invoice,
      status: "Paid",
      paidAmount: parsed,
      generatedReceiptUrl: `REC-${invoice.id}.pdf`
    });
    if (result?.ok) {
      const approvedStatus = String(result?.data?.status || "").trim();
      onNotify?.(
        approvedStatus === "Partially Paid" ? "Partial payment approved" : "Payment approved",
        approvedStatus === "Partially Paid"
          ? `Partial payment for invoice ${invoice.id} was approved. You can upload evidence for the remaining balance.`
          : `Invoice ${invoice.id} payment evidence was approved.`,
        "success"
      );
      showInvoiceWhatsappResult(result, "approved");
      loadStudentInvoices();
    }
    return result;
  };
  const handleReject = async () => {
    const invoice = rejectModal.invoice;
    if (!onUpdateInvoice || !invoice) return;
    const reason = String(rejectModal.reason || "").trim();
    if (!reason) {
      setRejectModal((prev) => ({ ...prev, error: "Please enter a rejection reason." }));
      return;
    }
    setIsRejecting(true);
    const result = await onUpdateInvoice({
      ...invoice,
      status: "Pending",
      paymentRejectionReason: reason
    });
    setIsRejecting(false);
    if (!result?.ok) {
      setRejectModal((prev) => ({ ...prev, error: result?.error || "Failed to reject payment evidence." }));
      return;
    }
    onNotify?.(
      "Payment evidence rejected",
      `Invoice ${invoice.id} payment evidence was rejected.`,
      "info"
    );
    showInvoiceWhatsappResult(result, "rejected");
    setRejectModal({ open: false, invoice: null, reason: "", error: "" });
    setIsDetailsModalOpen(false);
    loadStudentInvoices();
  };
  const handleResendInvoiceWhatsapp = async (invoice) => {
    if (!invoice?.id || !isStaff) {
      onNotify?.(
        "WhatsApp resend unavailable",
        "This action is only available to staff users.",
        "warning"
      );
      return;
    }
    setResendingInvoiceId(String(invoice.id));
    const result = await resendInvoiceWhatsapp(invoice.id, { actorRole: userRole });
    setResendingInvoiceId("");
    if (!result?.ok) {
      onNotify?.("WhatsApp resend failed", result?.error || "Could not resend invoice via WhatsApp.", "error");
      return;
    }
    const ws = result?.whatsappDelivery;
    const detail = ws?.reason ? ` ${ws.reason}` : "";
    if (ws?.status === "sent") {
      onNotify?.("WhatsApp sent", `Invoice ${invoice.id} was resent to student via WhatsApp.`, "success");
    } else {
      onNotify?.("WhatsApp not sent", `Invoice ${invoice.id} resend did not complete.${detail}`, "warning");
    }
    loadStudentInvoices();
  };
  const getStatusColor = (status) => {
    switch (status) {
      case "Paid":
        return "bg-emerald-50 text-emerald-700 border-emerald-200";
      case "Pending":
        return "bg-amber-50 text-amber-700 border-amber-200";
      case "Verifying":
        return "bg-blue-50 text-blue-700 border-blue-200";
      case "Overdue":
        return "bg-rose-50 text-rose-700 border-rose-200";
      case "Partially Paid":
        return "bg-violet-50 text-violet-700 border-violet-200";
      default:
        return "bg-slate-50 text-slate-700 border-slate-200";
    }
  };
  const roleNorm = String(userRole || "").trim().toLowerCase();
  const isCounselorStaff = isCounselorEquivalentAccountRole(userRole);
  const isStaff =
    ["admin", "manager", "team lead", "country coordinator"].includes(roleNorm) || isCounselorStaff;
  useEffect(() => {
    if (openCreateInvoice && isStaff) {
      setIsCreateOpen(true);
    }
  }, [openCreateInvoice, isStaff]);
  const canAcceptPayment =
    roleNorm === "admin" ||
    roleNorm === "manager" ||
    roleNorm === "accountant" ||
    (isCounselorStaff && counselorCanAcceptPayments);
  const canUploadEvidence = roleNorm === "student" || roleNorm === "country coordinator" || isCounselorStaff;
  const isStudentView = roleNorm === "student";
  const invoiceHasDeliveryDetails = (inv) => Boolean(
    inv?.paymentAccount || inv?.attachmentLink || inv?.attachmentFileUrl || inv?.generatedReceiptUrl
  );
  const hasRejectedPaymentEvidenceOnInvoice = hasRejectedPaymentEvidence;
  const paymentRows = buildPaymentTableRows(studentInvoices).sort((a, b) => {
    const dateA = new Date(a.evidence?.uploadedAt || 0).getTime();
    const dateB = new Date(b.evidence?.uploadedAt || 0).getTime();
    return dateB - dateA;
  });
  const openEvidenceModal = (inv, evidence = null) => {
    const claimed = evidence?.claimedAmount ?? inv?.paymentProofClaimedAmount;
    const approved = evidence?.approvedAmount;
    const parsedClaimed = Number(claimed);
    const parsedApproved = Number(approved);
    let defaultAmount = "";
    if (Number.isFinite(parsedApproved) && parsedApproved > 0) {
      defaultAmount = String(parsedApproved);
    } else if (Number.isFinite(parsedClaimed) && parsedClaimed > 0) {
      defaultAmount = String(parsedClaimed);
    }
    setEvidenceModal({
      open: true,
      invoice: inv,
      evidence,
      paidAmount: defaultAmount,
      error: "",
      saving: false
    });
  };
  const closeEvidenceModal = () => setEvidenceModal({ open: false, invoice: null, evidence: null, paidAmount: "", error: "", saving: false });
  const canUploadForInvoice = (inv) => {
    if (!canUploadEvidence) return false;
    const status = String(inv?.status || "").trim();
    if (status === "Verifying" || isInvoiceFullyPaid(inv)) return false;
    if (!invoiceProofUrl(inv)) return true;
    return hasRejectedPaymentEvidenceOnInvoice(inv);
  };
  const uploadableInvoices = studentInvoices.filter((inv) => canUploadForInvoice(inv));
  const handleOpenAddEvidence = () => {
    if (uploadableInvoices.length === 0) {
      onNotify?.(
        "Cannot upload yet",
        "No invoices are ready for a new receipt. Wait for review to finish or check the Ledger for open balances.",
        "info"
      );
      return;
    }
    handlePayClick(uploadableInvoices[0]);
  };
  const handleEvidenceInvoiceChange = (invoiceId) => {
    const invoice = uploadableInvoices.find((inv) => String(inv.id) === String(invoiceId));
    if (!invoice) return;
    setSelectedInvoice(invoice);
    setPaymentProofFile(null);
    setPaymentClaimedAmount("");
    setPaymentError("");
  };
  const renderInvoiceDeliveryPanel = (inv) => {
    if (!inv || !invoiceHasDeliveryDetails(inv)) return null;
    return /* @__PURE__ */ jsxs("div", { className: "rounded-xl border border-indigo-100 bg-indigo-50/70 p-4 space-y-3 text-sm", children: [
      /* @__PURE__ */ jsx("p", { className: "font-semibold text-indigo-900", children: isStudentView ? "How to pay this invoice" : "Invoice delivery details" }),
      inv.paymentAccount ? /* @__PURE__ */ jsxs("div", { className: "rounded-lg border border-white/80 bg-white/90 p-3 text-xs space-y-1", children: [
        /* @__PURE__ */ jsx("p", { className: "font-semibold text-slate-800", children: "Bank account" }),
        /* @__PURE__ */ jsxs("p", { children: [inv.paymentAccount.label, " · ", inv.paymentAccount.bankName] }),
        /* @__PURE__ */ jsxs("p", { className: "font-mono text-slate-900", children: [inv.paymentAccount.accountName, " — ", inv.paymentAccount.accountNumber] }),
        inv.paymentAccount.branch ? /* @__PURE__ */ jsxs("p", { children: ["Branch: ", inv.paymentAccount.branch] }) : null,
        inv.paymentAccount.currency ? /* @__PURE__ */ jsxs("p", { children: ["Currency: ", inv.paymentAccount.currency] }) : null,
        inv.paymentAccount.notes ? /* @__PURE__ */ jsxs("p", { className: "text-slate-600", children: [inv.paymentAccount.notes] }) : null
      ] }) : null,
      inv.attachmentLink ? /* @__PURE__ */ jsxs("p", { children: [
        /* @__PURE__ */ jsx("span", { className: "text-slate-600", children: "Reference link: " }),
        /* @__PURE__ */ jsx("a", { href: inv.attachmentLink, target: "_blank", rel: "noopener noreferrer", className: "text-indigo-700 font-semibold hover:underline break-all", children: inv.attachmentLink })
      ] }) : null,
      inv.attachmentFileUrl ? /* @__PURE__ */ jsxs("p", { children: [
        /* @__PURE__ */ jsx("span", { className: "text-slate-600", children: "Document: " }),
        /* @__PURE__ */ jsx("a", { href: inv.attachmentFileUrl, target: "_blank", rel: "noopener noreferrer", className: "text-indigo-700 font-semibold hover:underline", children: inv.attachmentFileName || "Download attachment" })
      ] }) : null,
      inv.generatedReceiptUrl ? /* @__PURE__ */ jsxs("p", { children: [
        /* @__PURE__ */ jsx("span", { className: "text-slate-600", children: "Invoice image: " }),
        /* @__PURE__ */ jsx("a", { href: inv.generatedReceiptUrl, target: "_blank", rel: "noopener noreferrer", className: "text-indigo-700 font-semibold hover:underline", children: "View invoice" })
      ] }) : null
    ] });
  };
  return /* @__PURE__ */ jsxs("div", { className: "space-y-6", children: [
    /* @__PURE__ */ jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [
      /* @__PURE__ */ jsxs("div", { className: "bg-white p-5 rounded-xl border border-gray-200 shadow-sm", children: [
        /* @__PURE__ */ jsxs("div", { className: "flex items-center gap-3 mb-2", children: [
          /* @__PURE__ */ jsx("div", { className: "p-2 bg-indigo-50 text-indigo-600 rounded-lg", children: /* @__PURE__ */ jsx(FileText, { size: 20 }) }),
          /* @__PURE__ */ jsx("span", { className: "text-xs font-bold text-slate-400 uppercase", children: "Total Invoiced" })
        ] }),
        /* @__PURE__ */ jsx("div", { className: "text-2xl font-bold text-slate-900", children: studentInvoices.length })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "bg-white p-5 rounded-xl border border-gray-200 shadow-sm", children: [
        /* @__PURE__ */ jsxs("div", { className: "flex items-center gap-3 mb-2", children: [
          /* @__PURE__ */ jsx("div", { className: "p-2 bg-emerald-50 text-emerald-600 rounded-lg", children: /* @__PURE__ */ jsx(CheckCircle, { size: 20 }) }),
          /* @__PURE__ */ jsx("span", { className: "text-xs font-bold text-slate-400 uppercase", children: "Total Paid" })
        ] }),
        /* @__PURE__ */ jsx("div", { className: "text-2xl font-bold text-slate-900", children: formatRawLKR(totalPaid) })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "bg-white p-5 rounded-xl border border-gray-200 shadow-sm", children: [
        /* @__PURE__ */ jsxs("div", { className: "flex items-center gap-3 mb-2", children: [
          /* @__PURE__ */ jsx("div", { className: "p-2 bg-amber-50 text-amber-600 rounded-lg", children: /* @__PURE__ */ jsx(Clock, { size: 20 }) }),
          /* @__PURE__ */ jsx("span", { className: "text-xs font-bold text-slate-400 uppercase", children: "Outstanding" })
        ] }),
        /* @__PURE__ */ jsx("div", { className: "text-2xl font-bold text-amber-600", children: formatRawLKR(totalPending) })
      ] })
    ] }),
    /* @__PURE__ */ jsxs("div", { className: "flex justify-between items-center", children: [
      /* @__PURE__ */ jsxs("div", { className: "space-y-1", children: [
        /* @__PURE__ */ jsxs("h3", { className: "font-bold text-slate-900 flex items-center gap-2", children: [
          /* @__PURE__ */ jsx(DollarSign, { size: 18, className: "text-slate-500" }),
          "Ledger & Payments"
        ] }),
        /* @__PURE__ */ jsxs("p", { className: "text-[10px] text-slate-400 flex items-center gap-1", children: [
          /* @__PURE__ */ jsx(Clock, { size: 10 }),
          " Rates updated: ",
          rateUpdatedAt,
          ratesLive ? "" : " (fallback)"
        ] }),
        /* @__PURE__ */ jsx("p", { className: "text-xs text-amber-700 font-medium", children: PAYMENT_NOT_REFUNDABLE_NOTICE })
      ] }),
      isStaff && /* @__PURE__ */ jsxs(Button, { size: "sm", onClick: () => setIsCreateOpen(true), children: [
        /* @__PURE__ */ jsx(Plus, { size: 16, className: "mr-2" }),
        " Create Invoice"
      ] })
    ] }),
    isCreateOpen && /* @__PURE__ */ jsx("div", { className: "fixed inset-0 z-50 overflow-y-auto overscroll-contain flex items-start justify-center py-8 px-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in", children: /* @__PURE__ */ jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-2xl p-6 w-full max-w-2xl scale-100 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto my-auto", children: [
      /* @__PURE__ */ jsxs("div", { className: "flex justify-between items-center mb-6", children: [
        /* @__PURE__ */ jsx("h3", { className: "font-bold text-lg text-slate-900", children: "New Invoice Details" }),
        /* @__PURE__ */ jsxs("button", { onClick: () => setIsCreateOpen(false), className: "text-slate-400 hover:text-slate-600", children: [
          /* @__PURE__ */ jsx("span", { className: "sr-only", children: "Close" }),
          /* @__PURE__ */ jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: /* @__PURE__ */ jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" }) })
        ] })
      ] }),
      /* @__PURE__ */ jsxs("form", { onSubmit: handleCreateSubmit, className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [
        createError ? /* @__PURE__ */ jsx("div", { className: "md:col-span-2 text-xs text-rose-600", children: createError }) : null,
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Description" }),
          /* @__PURE__ */ jsx(
            "input",
            {
              required: true,
              type: "text",
              className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
              placeholder: "e.g. Visa Fee",
              value: newDesc,
              onChange: (e) => setNewDesc(e.target.value)
            }
          )
        ] }),
        /* @__PURE__ */ jsxs("div", { children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Amount" }),
          /* @__PURE__ */ jsx(
            "input",
            {
              required: true,
              type: "number",
              className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
              placeholder: "0.00",
              value: newAmount,
              onChange: (e) => setNewAmount(e.target.value)
            }
          )
        ] }),
        /* @__PURE__ */ jsxs("div", { children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Currency" }),
          /* @__PURE__ */ jsxs(
            "select",
            {
              className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
              value: newCurrency,
              onChange: (e) => setNewCurrency(e.target.value),
              children: [
                /* @__PURE__ */ jsx("option", { children: "LKR" }),
                /* @__PURE__ */ jsx("option", { children: "USD" }),
                /* @__PURE__ */ jsx("option", { children: "GBP" }),
                /* @__PURE__ */ jsx("option", { children: "CAD" }),
                /* @__PURE__ */ jsx("option", { children: "AUD" })
              ]
            }
          )
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Due Date" }),
          /* @__PURE__ */ jsx(
            "input",
            {
              required: true,
              type: "date",
              className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
              value: newDueDate,
              onChange: (e) => setNewDueDate(e.target.value)
            }
          )
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Payment account" }),
          /* @__PURE__ */ jsxs("select", {
            className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500 disabled:bg-slate-50 disabled:text-slate-500",
            value: newPaymentAccountId,
            onChange: (e) => setNewPaymentAccountId(e.target.value),
            disabled: resolvedPaymentAccounts.length === 0,
            children: [
              /* @__PURE__ */ jsx("option", { value: "", children: resolvedPaymentAccounts.length === 0 ? "No accounts configured yet" : "None (no bank details on invoice)" }),
              resolvedPaymentAccounts.map((acct) => /* @__PURE__ */ jsxs("option", { value: acct.id, children: [
                acct.label,
                " — ",
                acct.bankName,
                " (",
                acct.currency || "LKR",
                ")"
              ] }, acct.id))
            ]
          }),
          resolvedPaymentAccounts.length === 0 ? /* @__PURE__ */ jsx("p", { className: "text-[11px] text-amber-700 mt-1.5", children: "Add bank accounts under Admin → Settings → Invoice payment accounts, then refresh this page." }) : null
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsxs("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1 flex items-center gap-1", children: [
            /* @__PURE__ */ jsx(Link2, { size: 12 }),
            " Reference link (optional)"
          ] }),
          /* @__PURE__ */ jsx("input", {
            type: "url",
            className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
            placeholder: "https://…",
            value: newAttachmentLink,
            onChange: (e) => setNewAttachmentLink(e.target.value)
          })
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Attachment for student (optional)" }),
          /* @__PURE__ */ jsxs("label", { className: "border-2 border-dashed border-gray-200 rounded-xl p-4 text-center hover:bg-slate-50 cursor-pointer transition-colors block", children: [
            /* @__PURE__ */ jsx("input", { type: "file", accept: ".jpg,.jpeg,.png,.pdf,.doc,.docx", className: "hidden", onChange: (event) => setNewAttachmentFile(event.target.files?.[0] || null) }),
            /* @__PURE__ */ jsx(Upload, { className: "mx-auto text-slate-400 mb-2", size: 22 }),
            /* @__PURE__ */ jsx("p", { className: "text-sm font-medium text-slate-600", children: newAttachmentFile ? newAttachmentFile.name : "Upload image, PDF, or document" }),
            /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-400 mt-1", children: `Sent with the invoice via WhatsApp when possible (max ${MAX_UPLOAD_LABEL})` })
          ] })
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2 flex gap-3 pt-2", children: [
          /* @__PURE__ */ jsx(Button, { type: "button", variant: "ghost", className: "flex-1", onClick: () => {
            setIsCreateOpen(false);
            resetCreateForm();
          }, children: "Cancel" }),
          /* @__PURE__ */ jsx(Button, { type: "submit", className: "flex-1", isLoading: isCreatingInvoice, children: "Issue Invoice" })
        ] })
      ] })
    ] }) }),
    /* @__PURE__ */ jsxs("div", { className: "space-y-2", children: [
      /* @__PURE__ */ jsx("h4", { className: "font-bold text-slate-800 text-sm", children: "Ledger" }),
      /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500", children: "All invoices for this student. Paid and balance due update when payments are approved in the Payments table below." })
    ] }),
    /* @__PURE__ */ jsx("div", { className: "bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm", children: /* @__PURE__ */ jsxs("table", { className: "w-full text-sm text-left", children: [
      /* @__PURE__ */ jsx("thead", { className: "bg-gray-50 border-b border-gray-200 text-slate-500 font-medium", children: /* @__PURE__ */ jsxs("tr", { children: [
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4", children: "Invoice" }),
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4", children: "Invoiced" }),
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4 text-right", children: "Details" })
      ] }) }),
      /* @__PURE__ */ jsx("tbody", { className: "divide-y divide-gray-100", children: invoicesLoading ? /* @__PURE__ */ jsx("tr", { children: /* @__PURE__ */ jsx("td", { colSpan: 3, className: "text-center py-8 text-slate-400", children: "Loading…" }) }) : studentInvoices.length === 0 ? /* @__PURE__ */ jsx("tr", { children: /* @__PURE__ */ jsx("td", { colSpan: 3, className: "text-center py-8 text-slate-400", children: "No invoices found." }) }) : studentInvoices.map((inv) => {
        return /* @__PURE__ */ jsxs("tr", { className: "hover:bg-slate-50 transition-colors", children: [
          /* @__PURE__ */ jsxs("td", { className: "px-6 py-4 font-medium text-slate-700", children: [
            /* @__PURE__ */ jsx("div", { className: "font-mono text-xs text-slate-500", children: inv.id }),
            inv.description,
            !isStudentView && inv.createdByName ? /* @__PURE__ */ jsxs("div", { className: "text-xs text-slate-500 mt-0.5", children: [
              "Created by: ",
              inv.createdByName
            ] }) : null,
            inv.issueDate ? /* @__PURE__ */ jsxs("div", { className: "text-xs text-slate-400 mt-0.5", children: [
              "Issued: ",
              inv.issueDate,
              inv.dueDate ? ` · Due: ${inv.dueDate}` : ""
            ] }) : null
          ] }),
          /* @__PURE__ */ jsx("td", { className: "px-6 py-4 font-mono text-slate-900", children: /* @__PURE__ */ jsxs("div", { className: "flex flex-col", children: [
            /* @__PURE__ */ jsxs("span", { className: "font-semibold", children: [
              inv.currency,
              " ",
              invoiceLedgerAmount(inv).toLocaleString()
            ] }),
            inv.currency !== "LKR" ? /* @__PURE__ */ jsxs("span", { className: "text-[10px] text-slate-400 font-normal", children: [
              "\u2248 ",
              formatLKR(invoiceLedgerAmount(inv), inv.currency, exchangeRates)
            ] }) : null
          ] }) }),
          /* @__PURE__ */ jsx("td", { className: "px-6 py-4 text-right", children: /* @__PURE__ */ jsx(Button, { size: "sm", variant: "outline", onClick: () => handleOpenDetails(inv), children: "View" }) })
        ] }, inv.id);
      }) })
    ] }) }),
    /* @__PURE__ */ jsxs("div", { className: "space-y-2 pt-2", children: [
      /* @__PURE__ */ jsxs("div", { className: "flex flex-wrap items-start justify-between gap-3", children: [
        /* @__PURE__ */ jsxs("div", { className: "space-y-1", children: [
          /* @__PURE__ */ jsx("h4", { className: "font-bold text-slate-800 text-sm", children: "Payments" }),
          /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500", children: isStudentView ? "Approved, pending, and rejected receipts — one row per slip. Upload new receipts with the button." : "Approved, pending, and rejected payment evidence. Open a pending row to approve and set the amount received; the ledger balances update automatically." })
        ] }),
        canUploadEvidence ? /* @__PURE__ */ jsxs(Button, { size: "sm", onClick: handleOpenAddEvidence, children: [
          /* @__PURE__ */ jsx(Plus, { size: 16, className: "mr-1.5" }),
          isStudentView ? "Add receipt" : "Add evidence"
        ] }) : null
      ] })
    ] }),
    /* @__PURE__ */ jsx("div", { className: "bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm", children: /* @__PURE__ */ jsxs("table", { className: "w-full text-sm text-left", children: [
      /* @__PURE__ */ jsx("thead", { className: "bg-gray-50 border-b border-gray-200 text-slate-500 font-medium", children: /* @__PURE__ */ jsxs("tr", { children: [
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4", children: "Date" }),
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4", children: "Status" }),
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4", children: "Amount" }),
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4 text-right", children: "Evidence" })
      ] }) }),
      /* @__PURE__ */ jsx("tbody", { className: "divide-y divide-gray-100", children: invoicesLoading ? /* @__PURE__ */ jsx("tr", { children: /* @__PURE__ */ jsx("td", { colSpan: 4, className: "text-center py-8 text-slate-400", children: "Loading…" }) }) : paymentRows.length === 0 ? /* @__PURE__ */ jsx("tr", { children: /* @__PURE__ */ jsx("td", { colSpan: 4, className: "text-center py-10", children: /* @__PURE__ */ jsxs("div", { className: "space-y-3", children: [
        /* @__PURE__ */ jsx("p", { className: "text-sm text-slate-500", children: isStudentView ? "No payment receipts yet." : "No payment evidence yet." }),
        canUploadEvidence ? /* @__PURE__ */ jsxs(Button, { size: "sm", onClick: handleOpenAddEvidence, children: [
          /* @__PURE__ */ jsx(Upload, { size: 16, className: "mr-1.5" }),
          isStudentView ? "Add receipt" : "Add evidence"
        ] }) : null
      ] }) }) }) : paymentRows.map((row) => {
        const inv = row.invoice;
        const evidence = row.evidence;
        const proofUrl = evidenceProofUrl(evidence);
        const showReupload = evidence.isCurrent && canUploadForInvoice(inv) && hasRejectedPaymentEvidenceOnInvoice(inv);
        const approvalLabel = getEvidenceApprovalLabel(evidence, inv);
        const approvalClass = getPaymentApprovalClass(approvalLabel);
        const rowAmount = evidenceDisplayAmount(evidence, inv);
        const paymentKind = evidencePaymentKind(evidence, inv);
        const paymentKindLabel = evidencePaymentKindLabel(paymentKind);
        const paymentKindClass = evidencePaymentKindClass(paymentKind);
        const rejectionNote = String(evidence?.rejectionReason || (evidence.isCurrent ? inv.paymentRejectionReason : "") || "").trim();
        const evidenceLabel = evidence?.name || null;
        const isPendingPayment = evidence.isCurrent && String(inv?.status || "").trim() === "Verifying";
        const canReviewCurrent = canAcceptPayment && isPendingPayment;
        return /* @__PURE__ */ jsxs("tr", { className: `hover:bg-slate-50 transition-colors ${isPendingPayment ? "bg-blue-50/40" : ""}`, children: [
          /* @__PURE__ */ jsxs("td", { className: "px-6 py-4", children: [
            /* @__PURE__ */ jsx("div", { className: "text-slate-800", children: formatPaymentTableDate(inv, evidence) }),
            /* @__PURE__ */ jsx("div", { className: "text-xs text-slate-400 mt-0.5", children: inv.description }),
            evidenceLabel ? /* @__PURE__ */ jsx("div", { className: "text-xs text-slate-500 mt-0.5 truncate max-w-[220px]", children: evidenceLabel }) : null,
            rejectionNote && approvalLabel === "Rejected" ? /* @__PURE__ */ jsxs("div", { className: "text-xs text-rose-600 mt-1", children: [
              "Feedback: ",
              rejectionNote
            ] }) : null
          ] }),
          /* @__PURE__ */ jsx("td", { className: "px-6 py-4", children: /* @__PURE__ */ jsx("span", { className: `inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-bold border ${approvalClass}`, children: approvalLabel }) }),
          /* @__PURE__ */ jsx("td", { className: "px-6 py-4 font-mono font-semibold text-slate-900", children: /* @__PURE__ */ jsxs("div", { className: "flex flex-col gap-1", children: [
            /* @__PURE__ */ jsxs("span", { children: [
              inv.currency,
              " ",
              rowAmount.toLocaleString()
            ] }),
            paymentKindLabel && paymentKind !== "partial" ? /* @__PURE__ */ jsx("span", { className: `inline-flex w-fit items-center px-2 py-0.5 rounded-full text-[10px] font-bold border ${paymentKindClass}`, children: paymentKindLabel }) : null
          ] }) }),
          /* @__PURE__ */ jsx("td", { className: "px-6 py-4 text-right", children: /* @__PURE__ */ jsxs("div", { className: "flex flex-wrap justify-end gap-2", children: [
            canReviewCurrent ? /* @__PURE__ */ jsx(Button, { size: "sm", className: "bg-indigo-600 hover:bg-indigo-700 text-white", onClick: () => openEvidenceModal(inv, evidence), children: "Approve" }) : /* @__PURE__ */ jsx(Button, { size: "sm", variant: "outline", onClick: () => openEvidenceModal(inv, evidence), children: proofUrl ? "View evidence" : "View details" }),
            showReupload ? /* @__PURE__ */ jsx(Button, { size: "sm", onClick: () => handlePayClick(inv), children: isStudentView ? "Re-upload receipt" : "Re-upload evidence" }) : null
          ] }) })
        ] }, row.rowKey);
      }) })
    ] }) }),
    isDetailsModalOpen && detailsInvoice && /* @__PURE__ */ jsx("div", { className: "fixed inset-0 z-50 overflow-y-auto overscroll-contain flex items-start justify-center py-8 px-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in", children: /* @__PURE__ */ jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-2xl p-6 w-full max-w-lg scale-100 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto my-auto", children: [
      /* @__PURE__ */ jsxs("div", { className: "flex justify-between items-center mb-4", children: [
        /* @__PURE__ */ jsx("h3", { className: "font-bold text-lg text-slate-900", children: "Invoice Details" }),
        /* @__PURE__ */ jsxs("button", { onClick: () => setIsDetailsModalOpen(false), className: "text-slate-400 hover:text-slate-600", children: [
          /* @__PURE__ */ jsx("span", { className: "sr-only", children: "Close" }),
          /* @__PURE__ */ jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: /* @__PURE__ */ jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" }) })
        ] })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "space-y-3 text-sm", children: [
        renderInvoiceDeliveryPanel(detailsInvoice),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Invoice ID: " }),
          /* @__PURE__ */ jsx("span", { className: "font-mono text-slate-800", children: detailsInvoice.id })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Description: " }),
          /* @__PURE__ */ jsx("span", { className: "font-semibold text-slate-800", children: detailsInvoice.description })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Amount: " }),
          /* @__PURE__ */ jsxs("span", { className: "font-semibold text-slate-800", children: [
            detailsInvoice.currency,
            " ",
            invoiceLedgerAmount(detailsInvoice).toLocaleString()
          ] })
        ] }),
        invoiceApprovedPaid(detailsInvoice) > 0 ? /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Paid so far: " }),
          /* @__PURE__ */ jsxs("span", { className: "font-semibold text-emerald-700", children: [
            detailsInvoice.currency,
            " ",
            invoiceApprovedPaid(detailsInvoice).toLocaleString()
          ] })
        ] }) : null,
        !isInvoiceFullyPaid(detailsInvoice) ? /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Balance due: " }),
          /* @__PURE__ */ jsxs("span", { className: "font-semibold text-amber-700", children: [
            detailsInvoice.currency,
            " ",
            invoiceBalanceDue(detailsInvoice).toLocaleString()
          ] })
        ] }) : null,
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Status: " }),
          /* @__PURE__ */ jsx("span", { className: "font-semibold text-slate-800", children: detailsInvoice.status })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Issue Date: " }),
          /* @__PURE__ */ jsx("span", { className: "text-slate-800", children: detailsInvoice.issueDate || "-" })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Due Date: " }),
          /* @__PURE__ */ jsx("span", { className: "text-slate-800", children: detailsInvoice.dueDate || "-" })
        ] }),
        /* @__PURE__ */ jsx("p", { className: "text-xs text-amber-700 font-medium pt-1", children: PAYMENT_NOT_REFUNDABLE_NOTICE })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "flex gap-3 mt-6 flex-wrap", children: [
        isStaff ? /* @__PURE__ */ jsx(
          Button,
          {
            variant: "outline",
            className: "flex-1 min-w-[140px]",
            onClick: () => handleResendInvoiceWhatsapp(detailsInvoice),
            disabled: resendingInvoiceId === String(detailsInvoice.id),
            children: resendingInvoiceId === String(detailsInvoice.id) ? "Sending…" : "Resend WhatsApp"
          }
        ) : null,
        /* @__PURE__ */ jsx(Button, { variant: "ghost", className: "flex-1", onClick: () => setIsDetailsModalOpen(false), children: "Close" })
      ] })
    ] }) }),
    isPaymentModalOpen && selectedInvoice && /* @__PURE__ */ jsx("div", { className: "fixed inset-0 z-50 overflow-y-auto overscroll-contain flex items-start justify-center py-8 px-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in", children: /* @__PURE__ */ jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-2xl p-6 w-full max-w-md scale-100 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto my-auto", children: [
      /* @__PURE__ */ jsxs("div", { className: "flex justify-between items-center mb-6", children: [
        /* @__PURE__ */ jsx("h3", { className: "font-bold text-lg text-slate-900", children: canUploadEvidence ? isStudentView ? "Upload receipt" : "Upload payment evidence" : "Process Payment" }),
        /* @__PURE__ */ jsxs("button", { onClick: () => setIsPaymentModalOpen(false), className: "text-slate-400 hover:text-slate-600", children: [
          /* @__PURE__ */ jsx("span", { className: "sr-only", children: "Close" }),
          /* @__PURE__ */ jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: /* @__PURE__ */ jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" }) })
        ] })
      ] }),
      canUploadEvidence && hasRejectedPaymentEvidenceOnInvoice(selectedInvoice) ? /* @__PURE__ */ jsx("p", { className: "text-xs text-rose-600 mb-6", children: "Previous receipt was rejected — upload a corrected slip" }) : null,
      !canUploadEvidence && /* @__PURE__ */ jsxs("div", { className: "mb-6 bg-slate-50 p-4 rounded-lg border border-slate-100", children: [
        /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500 uppercase font-bold mb-1", children: "Amount to be paid" }),
        /* @__PURE__ */ jsxs("p", { className: "text-2xl font-bold text-amber-700", children: [
          selectedInvoice.currency,
          " ",
          invoiceBalanceDue(selectedInvoice).toLocaleString()
        ] }),
        /* @__PURE__ */ jsxs("p", { className: "text-xs text-slate-600 mt-1", children: [
          "Invoiced ",
          selectedInvoice.currency,
          " ",
          invoiceInvoicedAmount(selectedInvoice).toLocaleString(),
          " · Paid ",
          selectedInvoice.currency,
          " ",
          invoiceApprovedPaid(selectedInvoice).toLocaleString()
        ] }),
        selectedInvoice.currency !== "LKR" && /* @__PURE__ */ jsxs("p", { className: "text-xs text-slate-400 mt-1", children: [
          "\u2248 ",
          formatLKR(invoiceBalanceDue(selectedInvoice), selectedInvoice.currency, exchangeRates)
        ] }),
        /* @__PURE__ */ jsx("p", { className: "text-sm text-slate-600 mt-2", children: selectedInvoice.description }),
        /* @__PURE__ */ jsx("p", { className: "text-xs text-amber-700 font-medium mt-3", children: PAYMENT_NOT_REFUNDABLE_NOTICE })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "space-y-4 mb-6", children: [
        !canUploadEvidence && /* @__PURE__ */ jsxs("label", { className: `flex items-center p-4 border rounded-xl cursor-pointer transition-all ${paymentMethod === "card" ? "border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500" : "border-gray-200 hover:border-gray-300"}`, children: [
          /* @__PURE__ */ jsx("input", { type: "radio", name: "payment", className: "sr-only", checked: paymentMethod === "card", onChange: () => setPaymentMethod("card") }),
          /* @__PURE__ */ jsx("div", { className: `w-5 h-5 rounded-full border mr-3 flex items-center justify-center ${paymentMethod === "card" ? "border-indigo-600" : "border-gray-300"}`, children: paymentMethod === "card" && /* @__PURE__ */ jsx("div", { className: "w-2.5 h-2.5 bg-indigo-600 rounded-full" }) }),
          /* @__PURE__ */ jsxs("div", { children: [
            /* @__PURE__ */ jsx("p", { className: "font-semibold text-slate-900", children: "Pay by Card" }),
            /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500", children: "Secure checkout via Stripe" })
          ] })
        ] }),
        /* @__PURE__ */ jsxs("label", { className: `flex items-center p-4 border rounded-xl cursor-pointer transition-all ${paymentMethod === "upload" ? "border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500" : "border-gray-200 hover:border-gray-300"}`, children: [
          /* @__PURE__ */ jsx("input", { type: "radio", name: "payment", className: "sr-only", checked: paymentMethod === "upload", onChange: () => setPaymentMethod("upload") }),
          /* @__PURE__ */ jsx("div", { className: `w-5 h-5 rounded-full border mr-3 flex items-center justify-center ${paymentMethod === "upload" ? "border-indigo-600" : "border-gray-300"}`, children: paymentMethod === "upload" && /* @__PURE__ */ jsx("div", { className: "w-2.5 h-2.5 bg-indigo-600 rounded-full" }) }),
          /* @__PURE__ */ jsxs("div", { children: [
            /* @__PURE__ */ jsx("p", { className: "font-semibold text-slate-900", children: "Bank Transfer" }),
            /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500", children: "Upload bank slip or transfer receipt" })
          ] })
        ] }),
        canUploadEvidence && !isStudentView && /* @__PURE__ */ jsxs("label", { className: `flex items-center p-4 border rounded-xl cursor-pointer transition-all ${paymentMethod === "cash" ? "border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500" : "border-gray-200 hover:border-gray-300"}`, children: [
          /* @__PURE__ */ jsx("input", { type: "radio", name: "payment", className: "sr-only", checked: paymentMethod === "cash", onChange: () => setPaymentMethod("cash") }),
          /* @__PURE__ */ jsx("div", { className: `w-5 h-5 rounded-full border mr-3 flex items-center justify-center ${paymentMethod === "cash" ? "border-indigo-600" : "border-gray-300"}`, children: paymentMethod === "cash" && /* @__PURE__ */ jsx("div", { className: "w-2.5 h-2.5 bg-indigo-600 rounded-full" }) }),
          /* @__PURE__ */ jsxs("div", { children: [
            /* @__PURE__ */ jsx("p", { className: "font-semibold text-slate-900", children: "Cash" }),
            /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500", children: "Record cash payment — receipt upload is optional" })
          ] })
        ] })
      ] }),
      paymentMethod !== "card" && /* @__PURE__ */ jsxs("div", { className: "mb-6 space-y-4", children: [
        /* @__PURE__ */ jsxs("div", { children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Amount on this receipt" }),
          /* @__PURE__ */ jsxs("div", { className: "flex items-center gap-3", children: [
            /* @__PURE__ */ jsx("span", { className: "text-sm font-medium text-slate-600 shrink-0", children: selectedInvoice.currency || "LKR" }),
            /* @__PURE__ */ jsx("input", {
              type: "number",
              min: "0",
              step: "0.01",
              className: "flex-1 px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
              placeholder: "0.00",
              value: paymentClaimedAmount,
              onChange: (event) => setPaymentClaimedAmount(event.target.value)
            })
          ] }),
          /* @__PURE__ */ jsx("p", { className: "text-[11px] text-slate-500 mt-1", children: paymentMethod === "cash" ? "Enter the cash amount paid. You can upload additional receipts until the invoice is fully paid." : "Enter the exact amount on this slip. You can upload additional receipts until the invoice is fully paid." })
        ] }),
        /* @__PURE__ */ jsxs("label", { className: "border-2 border-dashed border-gray-200 rounded-xl p-6 text-center hover:bg-slate-50 cursor-pointer transition-colors block", children: [
          /* @__PURE__ */ jsx("input", { type: "file", accept: ".jpg,.jpeg,.png,.pdf,.doc,.docx", className: "hidden", onChange: (event) => setPaymentProofFile(event.target.files?.[0] || null) }),
          /* @__PURE__ */ jsx(Upload, { className: "mx-auto text-slate-400 mb-2", size: 24 }),
          /* @__PURE__ */ jsx("p", { className: "text-sm font-medium text-slate-600", children: paymentProofFile ? paymentProofFile.name : paymentMethod === "cash" ? "Click to upload cash payment proof (optional)" : "Click to upload receipt" }),
          /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-400 mt-1", children: paymentMethod === "cash" ? `Optional — PDF, JPG, PNG, DOC, or DOCX (max ${MAX_UPLOAD_LABEL})` : `PDF, JPG, PNG, DOC, or DOCX (max ${MAX_UPLOAD_LABEL})` })
        ] })
      ] }),
      paymentError ? /* @__PURE__ */ jsx("p", { className: "text-xs text-rose-600 mb-4", children: paymentError }) : null,
      /* @__PURE__ */ jsxs("div", { className: "flex gap-3", children: [
        /* @__PURE__ */ jsx(Button, { variant: "ghost", className: "flex-1", onClick: () => setIsPaymentModalOpen(false), children: "Cancel" }),
        /* @__PURE__ */ jsx(Button, { className: "flex-1 bg-indigo-600 hover:bg-indigo-700 text-white", onClick: handlePaymentSubmit, isLoading: isSubmittingPayment, children: paymentMethod === "card" ? "Pay Now" : paymentMethod === "cash" ? "Submit Cash Payment" : "Submit Receipt" })
      ] })
    ] }) }),
    rejectModal.open && rejectModal.invoice && /* @__PURE__ */ jsx("div", { className: "fixed inset-0 z-[60] overflow-y-auto overscroll-contain flex items-start justify-center py-8 px-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in", children: /* @__PURE__ */ jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-2xl p-6 w-full max-w-md scale-100 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto my-auto", children: [
      /* @__PURE__ */ jsx("h3", { className: "font-bold text-lg text-slate-900 mb-2", children: "Reject payment evidence" }),
      /* @__PURE__ */ jsxs("p", { className: "text-sm text-slate-600 mb-4", children: [
        "Invoice ",
        rejectModal.invoice.id,
        " — provide a reason for the student."
      ] }),
      /* @__PURE__ */ jsx("textarea", { className: "w-full min-h-[100px] border border-gray-200 rounded-lg p-3 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500", placeholder: "Rejection reason...", value: rejectModal.reason, onChange: (event) => setRejectModal((prev) => ({ ...prev, reason: event.target.value, error: "" })) }),
      rejectModal.error ? /* @__PURE__ */ jsx("p", { className: "text-xs text-rose-600 mt-2", children: rejectModal.error }) : null,
      /* @__PURE__ */ jsxs("div", { className: "flex gap-3 mt-6", children: [
        /* @__PURE__ */ jsx(Button, { variant: "ghost", className: "flex-1", onClick: () => setRejectModal({ open: false, invoice: null, reason: "", error: "" }), children: "Cancel" }),
        /* @__PURE__ */ jsx(Button, { className: "flex-1 bg-rose-600 hover:bg-rose-700 text-white", onClick: handleReject, isLoading: isRejecting, children: "Reject Evidence" })
      ] })
    ] }) }),
    evidenceModal.open && evidenceModal.invoice && (() => {
      const modalInv = evidenceModal.invoice;
      const modalEvidence = evidenceModal.evidence;
      const modalProofUrl = modalEvidence ? evidenceProofUrl(modalEvidence) : invoiceProofUrl(modalInv);
      const modalProofName = modalEvidence?.name || modalInv.paymentProofName || "Payment evidence";
      const modalStatus = String(modalInv.status || "").trim();
      const isApproved = modalEvidence
        ? String(modalEvidence.outcome || "").trim() === "approved"
        : modalStatus === "Paid";
      const modalRowAmount = modalEvidence ? evidenceDisplayAmount(modalEvidence, modalInv) : invoiceApprovedPaid(modalInv);
      const studentClaimed = Number(modalEvidence?.claimedAmount ?? modalInv?.paymentProofClaimedAmount);
      const canEnterPaidAmount = canAcceptPayment && modalStatus === "Verifying" && (!modalEvidence || modalEvidence.isCurrent);
      const showModalReupload = modalEvidence?.isCurrent && canUploadForInvoice(modalInv) && hasRejectedPaymentEvidenceOnInvoice(modalInv);
      const modalRejectionNote = String(modalEvidence?.rejectionReason || (modalEvidence?.isCurrent ? modalInv.paymentRejectionReason : "") || "").trim();
      return /* @__PURE__ */ jsx("div", { className: "fixed inset-0 z-[60] overflow-y-auto overscroll-contain flex items-start justify-center py-8 px-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in", children: /* @__PURE__ */ jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-2xl p-6 w-full max-w-2xl scale-100 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto my-auto", children: [
        /* @__PURE__ */ jsxs("div", { className: "flex justify-between items-start gap-4 mb-4", children: [
          /* @__PURE__ */ jsxs("div", { children: [
            /* @__PURE__ */ jsx("h3", { className: "font-bold text-lg text-slate-900", children: canEnterPaidAmount ? "Approve payment" : "Payment evidence" }),
            /* @__PURE__ */ jsxs("p", { className: "text-sm text-slate-500 mt-1", children: [
              modalInv.description,
              " · ",
              modalInv.id
            ] })
          ] }),
          /* @__PURE__ */ jsx("button", { onClick: closeEvidenceModal, className: "text-slate-400 hover:text-slate-600", children: /* @__PURE__ */ jsx(X, { size: 20 }) })
        ] }),
        modalProofUrl ? isImageProof(modalProofUrl, modalProofName) ? /* @__PURE__ */ jsx("img", { src: modalProofUrl, alt: modalProofName, className: "max-w-full max-h-[min(50vh,420px)] mx-auto rounded-lg border border-slate-200 object-contain" }) : isPdfProof(modalProofUrl, modalProofName) ? /* @__PURE__ */ jsx("iframe", { title: modalProofName, src: modalProofUrl, className: "w-full h-[min(50vh,420px)] rounded-lg border border-slate-200 bg-slate-50" }) : /* @__PURE__ */ jsxs("div", { className: "text-center py-10 space-y-4", children: [
          /* @__PURE__ */ jsx(FileText, { size: 40, className: "mx-auto text-slate-400" }),
          /* @__PURE__ */ jsx("p", { className: "text-sm text-slate-600", children: modalProofName }),
          /* @__PURE__ */ jsx("a", { href: modalProofUrl, target: "_blank", rel: "noopener noreferrer", className: "inline-flex text-sm font-semibold text-indigo-600 hover:underline", children: "Open file in new tab" })
        ] }) : /* @__PURE__ */ jsx("p", { className: "text-sm text-slate-500 py-8 text-center", children: "No payment evidence file on this invoice." }),
        /* @__PURE__ */ jsxs("div", { className: "mt-6 pt-6 border-t border-slate-100 space-y-4", children: [
          Number.isFinite(studentClaimed) && studentClaimed > 0 ? /* @__PURE__ */ jsxs("p", { className: "text-xs text-slate-600", children: [
            "Student declared on receipt: ",
            /* @__PURE__ */ jsx("span", { className: "font-semibold text-slate-800", children: `${modalInv.currency || "LKR"} ${studentClaimed.toLocaleString()}` })
          ] }) : null,
          /* @__PURE__ */ jsx("p", { className: "text-sm font-semibold text-slate-900", children: isApproved ? "Amount approved" : "Amount to approve" }),
          isApproved ? /* @__PURE__ */ jsxs("p", { className: "text-sm font-mono font-semibold text-slate-800", children: [
            modalInv.currency || "LKR",
            " ",
            modalRowAmount.toLocaleString()
          ] }) : canEnterPaidAmount ? /* @__PURE__ */ jsxs(Fragment, { children: [
            /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500", children: "Enter or adjust the amount received on this receipt. Approving updates paid and remaining balance on the invoice." }),
            /* @__PURE__ */ jsxs("div", { className: "flex items-center gap-3", children: [
              /* @__PURE__ */ jsx("span", { className: "text-sm font-medium text-slate-600 shrink-0", children: modalInv.currency || "LKR" }),
              /* @__PURE__ */ jsx("input", {
                type: "number",
                min: "0",
                step: "0.01",
                disabled: evidenceModal.saving,
                className: "flex-1 px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500 disabled:bg-slate-50",
                placeholder: "0.00",
                value: evidenceModal.paidAmount,
                onChange: (event) => setEvidenceModal((prev) => ({ ...prev, paidAmount: event.target.value, error: "" }))
              })
            ] })
          ] }) : /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500", children: "Amount will be recorded when payment evidence is approved." }),
          evidenceModal.error ? /* @__PURE__ */ jsx("p", { className: "text-xs text-rose-600", children: evidenceModal.error }) : null,
          modalRejectionNote ? /* @__PURE__ */ jsxs("p", { className: "text-xs text-rose-600", children: [
            "Feedback: ",
            modalRejectionNote
          ] }) : null
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "flex gap-3 mt-6 flex-wrap", children: [
          modalProofUrl ? /* @__PURE__ */ jsx("a", { href: modalProofUrl, target: "_blank", rel: "noopener noreferrer", className: "flex-1 min-w-[140px]", children: /* @__PURE__ */ jsx(Button, { variant: "outline", className: "w-full", children: "Open in new tab" }) }) : null,
          showModalReupload ? /* @__PURE__ */ jsx(Button, { className: "flex-1 min-w-[140px] bg-indigo-600 hover:bg-indigo-700 text-white", onClick: () => {
            closeEvidenceModal();
            handlePayClick(modalInv);
          }, children: isStudentView ? "Re-upload receipt" : "Re-upload evidence" }) : null,
          canEnterPaidAmount ? /* @__PURE__ */ jsxs(Fragment, { children: [
            /* @__PURE__ */ jsx(Button, { className: "flex-1 min-w-[120px]", isLoading: evidenceModal.saving, onClick: async () => {
              setEvidenceModal((prev) => ({ ...prev, saving: true, error: "" }));
              const result = await handleApprove(modalInv, evidenceModal.paidAmount);
              if (!result?.ok) {
                setEvidenceModal((prev) => ({ ...prev, saving: false, error: result?.error || "Failed to approve payment." }));
                return;
              }
              closeEvidenceModal();
            }, children: "Approve" }),
            /* @__PURE__ */ jsx(Button, { variant: "outline", className: "flex-1 min-w-[120px] border-rose-200 text-rose-700 hover:bg-rose-50", disabled: evidenceModal.saving, onClick: () => {
              closeEvidenceModal();
              setRejectModal({ open: true, invoice: modalInv, reason: "", error: "" });
            }, children: "Reject" })
          ] }) : null,
          /* @__PURE__ */ jsx(Button, { variant: "ghost", className: "flex-1 min-w-[100px]", onClick: closeEvidenceModal, children: "Close" })
        ] })
      ] }) });
    })(),
    whatsappNotification.show && /* @__PURE__ */ jsx("div", { className: "fixed bottom-6 right-6 z-50 animate-in slide-in-from-bottom-5 fade-in duration-300", children: /* @__PURE__ */ jsxs("div", { className: "bg-white border border-emerald-100 shadow-xl rounded-lg p-4 flex items-start gap-3 max-w-sm", children: [
      /* @__PURE__ */ jsx("div", { className: "p-2 bg-emerald-50 rounded-full text-emerald-600", children: /* @__PURE__ */ jsx(MessageCircle, { size: 18 }) }),
      /* @__PURE__ */ jsxs("div", { className: "flex-1", children: [
        /* @__PURE__ */ jsx("p", { className: "text-sm font-bold text-slate-900", children: "WhatsApp Sent" }),
        /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-600 mt-1 leading-relaxed", children: whatsappNotification.message })
      ] }),
      /* @__PURE__ */ jsx("button", { onClick: () => setWhatsappNotification({ show: false, message: "" }), className: "text-slate-400 hover:text-slate-600", children: /* @__PURE__ */ jsx(X, { size: 16 }) })
    ] }) })
  ] });
};
export {
  FinanceModule
};
