import { Fragment, jsx, jsxs } from "react/jsx-runtime";
import { useCallback, useEffect, useState } from "react";
import { DollarSign, CheckCircle, Clock, FileText, Plus, Upload, X, MessageCircle, Link2 } from "lucide-react";
import { Button } from "./Button";
import { formatLKR, formatRawLKR } from "../utils";
import { isCounselorEquivalentAccountRole } from "../roles";
import { useExchangeRates } from "../useExchangeRates";
import { getPaymentAccounts, uploadInvoicePaymentProof, getInvoicesByStudentId } from "../authApi";
import { COMPANY_NAME } from "../companyConfig";
import { MAX_UPLOAD_BYTES, MAX_UPLOAD_LABEL } from "../uploadLimits";
const escapeInvoiceSvgText = (value) => String(value || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const generateInvoiceImageDataUrl = async ({ invoice, student, paymentAccount }) => {
  try {
    const amount = `${invoice.currency} ${Number(invoice.amount || 0).toLocaleString()}`;
    const studentName = escapeInvoiceSvgText(student?.name || "Student");
    const description = escapeInvoiceSvgText(invoice.description || "");
    const dueDate = escapeInvoiceSvgText(invoice.dueDate || "-");
    const issuedDate = escapeInvoiceSvgText(invoice.issueDate || "-");
    const invoiceId = escapeInvoiceSvgText(invoice.id || "");
    const payLines = paymentAccount
      ? [
          escapeInvoiceSvgText(paymentAccount.bankName || ""),
          escapeInvoiceSvgText(`${paymentAccount.accountName || ""} · ${paymentAccount.accountNumber || ""}`)
        ].filter(Boolean)
      : [];
    const svgHeight = payLines.length ? 760 : 680;
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${svgHeight}" viewBox="0 0 1200 ${svgHeight}">
      <defs>
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="#eef2ff" />
          <stop offset="100%" stop-color="#f8fafc" />
        </linearGradient>
      </defs>
      <rect x="0" y="0" width="1200" height="${svgHeight}" fill="url(#bg)" />
      <rect x="40" y="40" width="1120" height="${svgHeight - 80}" rx="24" fill="#ffffff" stroke="#e2e8f0" />
      <text x="88" y="190" font-family="Arial, sans-serif" font-size="42" font-weight="700" fill="#1e293b">${escapeInvoiceSvgText(`${COMPANY_NAME} Invoice`)}</text>
      <text x="88" y="238" font-family="Arial, sans-serif" font-size="24" fill="#475569">Invoice ID: ${invoiceId}</text>
      <text x="88" y="290" font-family="Arial, sans-serif" font-size="22" fill="#64748b">Student</text>
      <text x="88" y="328" font-family="Arial, sans-serif" font-size="30" font-weight="600" fill="#0f172a">${studentName}</text>
      <text x="88" y="390" font-family="Arial, sans-serif" font-size="22" fill="#64748b">Description</text>
      <text x="88" y="428" font-family="Arial, sans-serif" font-size="28" fill="#0f172a">${description}</text>
      <text x="88" y="490" font-family="Arial, sans-serif" font-size="22" fill="#64748b">Issue Date</text>
      <text x="88" y="528" font-family="Arial, sans-serif" font-size="28" fill="#0f172a">${issuedDate}</text>
      <text x="88" y="570" font-family="Arial, sans-serif" font-size="22" fill="#64748b">Due Date</text>
      <text x="88" y="608" font-family="Arial, sans-serif" font-size="28" fill="#0f172a">${dueDate}</text>
      <rect x="760" y="240" width="340" height="220" rx="20" fill="#eef2ff" stroke="#c7d2fe" />
      <text x="790" y="310" font-family="Arial, sans-serif" font-size="22" fill="#4338ca">Total Amount</text>
      <text x="790" y="380" font-family="Arial, sans-serif" font-size="46" font-weight="700" fill="#312e81">${escapeInvoiceSvgText(amount)}</text>
      ${payLines.length ? `<text x="88" y="650" font-family="Arial, sans-serif" font-size="20" fill="#64748b">Pay to</text>
      <text x="88" y="688" font-family="Arial, sans-serif" font-size="24" fill="#0f172a">${payLines[0] || ""}</text>
      <text x="88" y="724" font-family="Arial, sans-serif" font-size="22" fill="#334155">${payLines[1] || ""}</text>` : ""}
      <text x="760" y="${svgHeight - 60}" font-family="Arial, sans-serif" font-size="20" fill="#64748b">Generated by ${escapeInvoiceSvgText(COMPANY_NAME)}</text>
    </svg>`;
    const encodedSvg = btoa(unescape(encodeURIComponent(svg)));
    const image = await new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => reject(new Error("invoice_image_render_failed"));
      img.src = `data:image/svg+xml;base64,${encodedSvg}`;
    });
    const canvas = document.createElement("canvas");
    canvas.width = 1200;
    canvas.height = svgHeight;
    const context = canvas.getContext("2d");
    if (!context) return "";
    context.fillStyle = "#ffffff";
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.drawImage(image, 0, 0, canvas.width, canvas.height);
    const logo = await new Promise((resolve) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => resolve(null);
      img.src = "/assets/company-full-logo.png";
    });
    if (logo) {
      const logoMaxWidth = 360;
      const logoHeight = 66;
      context.drawImage(logo, 88, 72, logoMaxWidth, logoHeight);
    }
    return canvas.toDataURL("image/png");
  } catch {
    return "";
  }
};
const INVOICE_ATTACHMENT_TYPES = new Set([
  "application/pdf",
  "image/png",
  "image/jpeg",
  "image/jpg",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
]);

const FinanceModule = ({ student, userRole, paymentAccounts = [], onCreateInvoice, onUpdateInvoice, onNotify, openCreateInvoice }) => {
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [newAmount, setNewAmount] = useState("");
  const [newDesc, setNewDesc] = useState("");
  const [newCurrency, setNewCurrency] = useState("LKR");
  const [newDueDate, setNewDueDate] = useState("");
  const [newAttachmentLink, setNewAttachmentLink] = useState("");
  const [newAttachmentFile, setNewAttachmentFile] = useState(null);
  const [newPaymentAccountId, setNewPaymentAccountId] = useState("");
  const [resolvedPaymentAccounts, setResolvedPaymentAccounts] = useState(
    Array.isArray(paymentAccounts) ? paymentAccounts : []
  );
  const [createError, setCreateError] = useState("");
  const [isCreatingInvoice, setIsCreatingInvoice] = useState(false);
  const { rates: exchangeRates, updatedAt: rateUpdatedAt, live: ratesLive } = useExchangeRates();

  const [studentInvoices, setStudentInvoices] = useState([]);
  const [invoicesLoading, setInvoicesLoading] = useState(true);

  const loadStudentInvoices = useCallback(async () => {
    const sid = String(student?.id || "").trim();
    if (!sid) { setStudentInvoices([]); setInvoicesLoading(false); return; }
    setInvoicesLoading(true);
    const result = await getInvoicesByStudentId(sid);
    if (result.ok) setStudentInvoices(result.data);
    setInvoicesLoading(false);
  }, [student?.id]);

  useEffect(() => { loadStudentInvoices(); }, [loadStudentInvoices]);

  useEffect(() => {
    setResolvedPaymentAccounts(Array.isArray(paymentAccounts) ? paymentAccounts : []);
  }, [paymentAccounts]);

  const refreshPaymentAccounts = () => {
    return getPaymentAccounts().then((result) => {
      if (result.ok && Array.isArray(result.data)) {
        setResolvedPaymentAccounts(result.data);
      }
      return result;
    });
  };

  useEffect(() => {
    if (!onCreateInvoice) return;
    let cancelled = false;
    refreshPaymentAccounts().then(() => {
      if (cancelled) return;
    });
    return () => {
      cancelled = true;
    };
  }, [onCreateInvoice]);

  useEffect(() => {
    if (!isCreateOpen || !onCreateInvoice) return;
    refreshPaymentAccounts();
  }, [isCreateOpen, onCreateInvoice]);
  const totalPaid = studentInvoices.filter((i) => i.status === "Paid").reduce((acc, curr) => acc + curr.amount * (exchangeRates[curr.currency] || 1), 0);
  const totalPending = studentInvoices.filter((i) => i.status === "Pending" || i.status === "Overdue" || i.status === "Verifying").reduce((acc, curr) => acc + curr.amount * (exchangeRates[curr.currency] || 1), 0);
  const resetCreateForm = () => {
    setNewAmount("");
    setNewDesc("");
    setNewDueDate("");
    setNewAttachmentLink("");
    setNewAttachmentFile(null);
    setNewPaymentAccountId("");
    setCreateError("");
  };

  const handleCreateSubmit = async (e) => {
    e.preventDefault();
    if (!onCreateInvoice) return;
    setCreateError("");
    const linkTrimmed = String(newAttachmentLink || "").trim();
    if (linkTrimmed && !/^https?:\/\//i.test(linkTrimmed)) {
      setCreateError("Reference link must start with http:// or https://");
      return;
    }
    if (newAttachmentFile) {
      if (newAttachmentFile.type && !INVOICE_ATTACHMENT_TYPES.has(newAttachmentFile.type)) {
        setCreateError("Unsupported attachment. Use PDF, JPG, PNG, DOC, or DOCX.");
        return;
      }
      if (newAttachmentFile.size > MAX_UPLOAD_BYTES) {
        setCreateError(`Attachment must be under ${MAX_UPLOAD_LABEL}.`);
        return;
      }
    }
    setIsCreatingInvoice(true);
    setIsCreateOpen(false);
    onNotify?.(
      "Invoice generation started",
      "The invoice popup is closed. Generation is running in the background and you will get an update in about 2-3 minutes.",
      "info",
      student?.id ? { studentId: student.id, view: "finance" } : null,
      7e3
    );
    const newInv = {
      id: `INV-${Date.now()}`,
      studentId: student.id,
      amount: parseFloat(newAmount),
      currency: newCurrency,
      description: newDesc,
      issueDate: (/* @__PURE__ */ new Date()).toISOString().split("T")[0],
      dueDate: newDueDate,
      status: "Pending"
    };
    const selectedAccount = resolvedPaymentAccounts.find((a) => String(a.id) === String(newPaymentAccountId));
    let invoiceAttachmentDataUrl;
    if (newAttachmentFile) {
      invoiceAttachmentDataUrl = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result || ""));
        reader.onerror = () => reject(new Error("read_error"));
        reader.readAsDataURL(newAttachmentFile);
      }).catch(() => "");
      if (!invoiceAttachmentDataUrl) {
        setCreateError("Unable to read attachment file.");
        setIsCreatingInvoice(false);
        return;
      }
    }
    const invoiceImageDataUrl = await generateInvoiceImageDataUrl({ invoice: newInv, student, paymentAccount: selectedAccount });
    const result = await onCreateInvoice({
      ...newInv,
      attachmentLink: linkTrimmed || void 0,
      paymentAccountId: newPaymentAccountId || void 0,
      invoiceAttachmentDataUrl: invoiceAttachmentDataUrl || void 0,
      invoiceAttachmentName: newAttachmentFile?.name,
      receiptImageDataUrl: invoiceImageDataUrl || void 0,
      receiptImageName: `${newInv.id}.png`
    });
    setIsCreatingInvoice(false);
    if (!result?.ok) {
      setCreateError(result?.error || "Failed to create invoice.");
      setIsCreateOpen(true);
      return;
    }
    resetCreateForm();
    onNotify?.(
      "Invoice generated",
      `Invoice ${result?.data?.id || newInv.id} is ready. We will keep you updated if any further processing is needed.`,
      "success",
      student?.id ? { studentId: student.id, view: "finance" } : null,
      7e3
    );
    loadStudentInvoices();
  };
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState(null);
  const [isDetailsModalOpen, setIsDetailsModalOpen] = useState(false);
  const [detailsInvoice, setDetailsInvoice] = useState(null);
  const [paymentMethod, setPaymentMethod] = useState("card");
  const [paymentProofFile, setPaymentProofFile] = useState(null);
  const [paymentError, setPaymentError] = useState("");
  const [isSubmittingPayment, setIsSubmittingPayment] = useState(false);
  const [rejectModal, setRejectModal] = useState({ open: false, invoice: null, reason: "", error: "" });
  const [isRejecting, setIsRejecting] = useState(false);
  const [whatsappNotification, setWhatsappNotification] = useState({ show: false, message: "" });
  const showWhatsappNotification = (message) => {
    setWhatsappNotification({ show: true, message });
    setTimeout(() => setWhatsappNotification({ show: false, message: "" }), 4e3);
  };
  const showInvoiceWhatsappResult = (result, decisionLabel) => {
    const ws = result?.invoiceWhatsappNotification?.whatsapp;
    if (ws?.status === "sent") {
      showWhatsappNotification(
        `Invoice payment evidence was ${decisionLabel}. WhatsApp sent to the student from the counselor's linked account.`
      );
    } else if (ws?.status === "failed" || ws?.status === "skipped") {
      const detail = ws?.reason ? ` ${ws.reason}` : "";
      showWhatsappNotification(
        `Invoice payment evidence was ${decisionLabel}. WhatsApp was not sent.${detail}`
      );
    }
  };
  const handlePayClick = (invoice) => {
    setSelectedInvoice(invoice);
    setIsPaymentModalOpen(true);
    setPaymentMethod(canUploadEvidence ? "upload" : "card");
    setPaymentProofFile(null);
    setPaymentError("");
  };
  const handleOpenDetails = (invoice) => {
    setDetailsInvoice(invoice);
    setIsDetailsModalOpen(true);
  };
  const handlePaymentSubmit = async () => {
    if (!onUpdateInvoice || !selectedInvoice) return;
    setPaymentError("");
    setIsSubmittingPayment(true);
    if (canUploadEvidence && paymentMethod === "card") {
      setPaymentError("Use Bank Transfer and upload a receipt or document for verification (card checkout is not used for evidence).");
      setIsSubmittingPayment(false);
      return;
    }
    if (paymentMethod === "card") {
      const result = await onUpdateInvoice({
        ...selectedInvoice,
        status: "Paid",
        paymentMethod: "Credit Card",
        generatedReceiptUrl: `REC-${selectedInvoice.id}.pdf`
      });
      if (!result?.ok) {
        setPaymentError(result?.error || "Failed to complete payment.");
        setIsSubmittingPayment(false);
        return;
      }
    } else {
      if (!paymentProofFile) {
        setPaymentError("Please upload payment proof.");
        setIsSubmittingPayment(false);
        return;
      }
      const proofAllowedTypes = new Set([
        "application/pdf",
        "image/png",
        "image/jpeg",
        "image/jpg",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      ]);
      if (paymentProofFile.type && !proofAllowedTypes.has(paymentProofFile.type)) {
        setPaymentError("Unsupported format. Use PDF, JPG, PNG, DOC, or DOCX.");
        setIsSubmittingPayment(false);
        return;
      }
      if (paymentProofFile.size > MAX_UPLOAD_BYTES) {
        setPaymentError(`Proof file must be under ${MAX_UPLOAD_LABEL}.`);
        setIsSubmittingPayment(false);
        return;
      }
      const dataUrl = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result || ""));
        reader.onerror = () => reject(new Error("read_error"));
        reader.readAsDataURL(paymentProofFile);
      }).catch(() => "");
      if (!dataUrl) {
        setPaymentError("Unable to read payment proof file.");
        setIsSubmittingPayment(false);
        return;
      }
      const uploadResult = await uploadInvoicePaymentProof(selectedInvoice.id, dataUrl, paymentProofFile.name);
      if (!uploadResult.ok) {
        setPaymentError(uploadResult.error || "Failed to upload payment proof.");
        setIsSubmittingPayment(false);
        return;
      }
      const updateResult = await onUpdateInvoice(uploadResult.data);
      if (!updateResult?.ok) {
        setPaymentError(updateResult?.error || "Payment proof uploaded but status update failed.");
        setIsSubmittingPayment(false);
        return;
      }
      onNotify?.(
        "Evidence uploaded",
        `Payment evidence for invoice ${selectedInvoice.id} was submitted for review.`,
        "success"
      );
    }
    setIsSubmittingPayment(false);
    setIsPaymentModalOpen(false);
    setSelectedInvoice(null);
    setPaymentProofFile(null);
    loadStudentInvoices();
  };
  const handleApprove = async (invoice) => {
    if (!onUpdateInvoice) return;
    const result = await onUpdateInvoice({
      ...invoice,
      status: "Paid",
      generatedReceiptUrl: `REC-${invoice.id}.pdf`
    });
    if (result?.ok) {
      onNotify?.(
        "Payment approved",
        `Invoice ${invoice.id} payment evidence was approved.`,
        "success"
      );
      showInvoiceWhatsappResult(result, "approved");
      loadStudentInvoices();
    }
    return result;
  };
  const handleReject = async () => {
    const invoice = rejectModal.invoice;
    if (!onUpdateInvoice || !invoice) return;
    const reason = String(rejectModal.reason || "").trim();
    if (!reason) {
      setRejectModal((prev) => ({ ...prev, error: "Please enter a rejection reason." }));
      return;
    }
    setIsRejecting(true);
    const result = await onUpdateInvoice({
      ...invoice,
      status: "Pending",
      paymentRejectionReason: reason
    });
    setIsRejecting(false);
    if (!result?.ok) {
      setRejectModal((prev) => ({ ...prev, error: result?.error || "Failed to reject payment evidence." }));
      return;
    }
    onNotify?.(
      "Payment evidence rejected",
      `Invoice ${invoice.id} payment evidence was rejected.`,
      "info"
    );
    showInvoiceWhatsappResult(result, "rejected");
    setRejectModal({ open: false, invoice: null, reason: "", error: "" });
    setIsDetailsModalOpen(false);
    loadStudentInvoices();
  };
  const getStatusColor = (status) => {
    switch (status) {
      case "Paid":
        return "bg-emerald-50 text-emerald-700 border-emerald-200";
      case "Pending":
        return "bg-amber-50 text-amber-700 border-amber-200";
      case "Verifying":
        return "bg-blue-50 text-blue-700 border-blue-200";
      case "Overdue":
        return "bg-rose-50 text-rose-700 border-rose-200";
      default:
        return "bg-slate-50 text-slate-700 border-slate-200";
    }
  };
  const roleNorm = String(userRole || "").trim().toLowerCase();
  const isCounselorStaff = isCounselorEquivalentAccountRole(userRole);
  const isStaff =
    ["admin", "manager", "team lead", "country coordinator"].includes(roleNorm) || isCounselorStaff;
  useEffect(() => {
    if (openCreateInvoice && isStaff) {
      setIsCreateOpen(true);
    }
  }, [openCreateInvoice, isStaff]);
  const canAcceptPayment =
    roleNorm === "admin" || roleNorm === "manager" || roleNorm === "accountant";
  const canUploadEvidence = roleNorm === "student" || roleNorm === "country coordinator" || isCounselorStaff;
  const isStudentView = roleNorm === "student";
  const invoiceHasDeliveryDetails = (inv) => Boolean(
    inv?.paymentAccount || inv?.attachmentLink || inv?.attachmentFileUrl || inv?.generatedReceiptUrl
  );
  const renderInvoiceDeliveryPanel = (inv) => {
    if (!inv || !invoiceHasDeliveryDetails(inv)) return null;
    return /* @__PURE__ */ jsxs("div", { className: "rounded-xl border border-indigo-100 bg-indigo-50/70 p-4 space-y-3 text-sm", children: [
      /* @__PURE__ */ jsx("p", { className: "font-semibold text-indigo-900", children: isStudentView ? "How to pay this invoice" : "Invoice delivery details" }),
      inv.paymentAccount ? /* @__PURE__ */ jsxs("div", { className: "rounded-lg border border-white/80 bg-white/90 p-3 text-xs space-y-1", children: [
        /* @__PURE__ */ jsx("p", { className: "font-semibold text-slate-800", children: "Bank account" }),
        /* @__PURE__ */ jsxs("p", { children: [inv.paymentAccount.label, " · ", inv.paymentAccount.bankName] }),
        /* @__PURE__ */ jsxs("p", { className: "font-mono text-slate-900", children: [inv.paymentAccount.accountName, " — ", inv.paymentAccount.accountNumber] }),
        inv.paymentAccount.branch ? /* @__PURE__ */ jsxs("p", { children: ["Branch: ", inv.paymentAccount.branch] }) : null,
        inv.paymentAccount.currency ? /* @__PURE__ */ jsxs("p", { children: ["Currency: ", inv.paymentAccount.currency] }) : null,
        inv.paymentAccount.notes ? /* @__PURE__ */ jsxs("p", { className: "text-slate-600", children: [inv.paymentAccount.notes] }) : null
      ] }) : null,
      inv.attachmentLink ? /* @__PURE__ */ jsxs("p", { children: [
        /* @__PURE__ */ jsx("span", { className: "text-slate-600", children: "Reference link: " }),
        /* @__PURE__ */ jsx("a", { href: inv.attachmentLink, target: "_blank", rel: "noopener noreferrer", className: "text-indigo-700 font-semibold hover:underline break-all", children: inv.attachmentLink })
      ] }) : null,
      inv.attachmentFileUrl ? /* @__PURE__ */ jsxs("p", { children: [
        /* @__PURE__ */ jsx("span", { className: "text-slate-600", children: "Document: " }),
        /* @__PURE__ */ jsx("a", { href: inv.attachmentFileUrl, target: "_blank", rel: "noopener noreferrer", className: "text-indigo-700 font-semibold hover:underline", children: inv.attachmentFileName || "Download attachment" })
      ] }) : null,
      inv.generatedReceiptUrl ? /* @__PURE__ */ jsxs("p", { children: [
        /* @__PURE__ */ jsx("span", { className: "text-slate-600", children: "Invoice image: " }),
        /* @__PURE__ */ jsx("a", { href: inv.generatedReceiptUrl, target: "_blank", rel: "noopener noreferrer", className: "text-indigo-700 font-semibold hover:underline", children: "View invoice" })
      ] }) : null
    ] });
  };
  return /* @__PURE__ */ jsxs("div", { className: "space-y-6", children: [
    /* @__PURE__ */ jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [
      /* @__PURE__ */ jsxs("div", { className: "bg-white p-5 rounded-xl border border-gray-200 shadow-sm", children: [
        /* @__PURE__ */ jsxs("div", { className: "flex items-center gap-3 mb-2", children: [
          /* @__PURE__ */ jsx("div", { className: "p-2 bg-indigo-50 text-indigo-600 rounded-lg", children: /* @__PURE__ */ jsx(FileText, { size: 20 }) }),
          /* @__PURE__ */ jsx("span", { className: "text-xs font-bold text-slate-400 uppercase", children: "Total Invoiced" })
        ] }),
        /* @__PURE__ */ jsx("div", { className: "text-2xl font-bold text-slate-900", children: studentInvoices.length })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "bg-white p-5 rounded-xl border border-gray-200 shadow-sm", children: [
        /* @__PURE__ */ jsxs("div", { className: "flex items-center gap-3 mb-2", children: [
          /* @__PURE__ */ jsx("div", { className: "p-2 bg-emerald-50 text-emerald-600 rounded-lg", children: /* @__PURE__ */ jsx(CheckCircle, { size: 20 }) }),
          /* @__PURE__ */ jsx("span", { className: "text-xs font-bold text-slate-400 uppercase", children: "Total Paid" })
        ] }),
        /* @__PURE__ */ jsx("div", { className: "text-2xl font-bold text-slate-900", children: formatRawLKR(totalPaid) })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "bg-white p-5 rounded-xl border border-gray-200 shadow-sm", children: [
        /* @__PURE__ */ jsxs("div", { className: "flex items-center gap-3 mb-2", children: [
          /* @__PURE__ */ jsx("div", { className: "p-2 bg-amber-50 text-amber-600 rounded-lg", children: /* @__PURE__ */ jsx(Clock, { size: 20 }) }),
          /* @__PURE__ */ jsx("span", { className: "text-xs font-bold text-slate-400 uppercase", children: "Outstanding" })
        ] }),
        /* @__PURE__ */ jsx("div", { className: "text-2xl font-bold text-amber-600", children: formatRawLKR(totalPending) })
      ] })
    ] }),
    /* @__PURE__ */ jsxs("div", { className: "flex justify-between items-center", children: [
      /* @__PURE__ */ jsxs("div", { className: "space-y-1", children: [
        /* @__PURE__ */ jsxs("h3", { className: "font-bold text-slate-900 flex items-center gap-2", children: [
          /* @__PURE__ */ jsx(DollarSign, { size: 18, className: "text-slate-500" }),
          "Ledger & Payments"
        ] }),
        /* @__PURE__ */ jsxs("p", { className: "text-[10px] text-slate-400 flex items-center gap-1", children: [
          /* @__PURE__ */ jsx(Clock, { size: 10 }),
          " Rates updated: ",
          rateUpdatedAt,
          ratesLive ? "" : " (fallback)"
        ] })
      ] }),
      isStaff && /* @__PURE__ */ jsxs(Button, { size: "sm", onClick: () => setIsCreateOpen(true), children: [
        /* @__PURE__ */ jsx(Plus, { size: 16, className: "mr-2" }),
        " Create Invoice"
      ] })
    ] }),
    isCreateOpen && /* @__PURE__ */ jsx("div", { className: "fixed inset-0 z-50 overflow-y-auto overscroll-contain flex items-start justify-center py-8 px-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in", children: /* @__PURE__ */ jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-2xl p-6 w-full max-w-2xl scale-100 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto my-auto", children: [
      /* @__PURE__ */ jsxs("div", { className: "flex justify-between items-center mb-6", children: [
        /* @__PURE__ */ jsx("h3", { className: "font-bold text-lg text-slate-900", children: "New Invoice Details" }),
        /* @__PURE__ */ jsxs("button", { onClick: () => setIsCreateOpen(false), className: "text-slate-400 hover:text-slate-600", children: [
          /* @__PURE__ */ jsx("span", { className: "sr-only", children: "Close" }),
          /* @__PURE__ */ jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: /* @__PURE__ */ jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" }) })
        ] })
      ] }),
      /* @__PURE__ */ jsxs("form", { onSubmit: handleCreateSubmit, className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [
        createError ? /* @__PURE__ */ jsx("div", { className: "md:col-span-2 text-xs text-rose-600", children: createError }) : null,
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Description" }),
          /* @__PURE__ */ jsx(
            "input",
            {
              required: true,
              type: "text",
              className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
              placeholder: "e.g. Visa Fee",
              value: newDesc,
              onChange: (e) => setNewDesc(e.target.value)
            }
          )
        ] }),
        /* @__PURE__ */ jsxs("div", { children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Amount" }),
          /* @__PURE__ */ jsx(
            "input",
            {
              required: true,
              type: "number",
              className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
              placeholder: "0.00",
              value: newAmount,
              onChange: (e) => setNewAmount(e.target.value)
            }
          )
        ] }),
        /* @__PURE__ */ jsxs("div", { children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Currency" }),
          /* @__PURE__ */ jsxs(
            "select",
            {
              className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
              value: newCurrency,
              onChange: (e) => setNewCurrency(e.target.value),
              children: [
                /* @__PURE__ */ jsx("option", { children: "LKR" }),
                /* @__PURE__ */ jsx("option", { children: "USD" }),
                /* @__PURE__ */ jsx("option", { children: "GBP" }),
                /* @__PURE__ */ jsx("option", { children: "CAD" }),
                /* @__PURE__ */ jsx("option", { children: "AUD" })
              ]
            }
          )
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Due Date" }),
          /* @__PURE__ */ jsx(
            "input",
            {
              required: true,
              type: "date",
              className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
              value: newDueDate,
              onChange: (e) => setNewDueDate(e.target.value)
            }
          )
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Payment account" }),
          /* @__PURE__ */ jsxs("select", {
            className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500 disabled:bg-slate-50 disabled:text-slate-500",
            value: newPaymentAccountId,
            onChange: (e) => setNewPaymentAccountId(e.target.value),
            disabled: resolvedPaymentAccounts.length === 0,
            children: [
              /* @__PURE__ */ jsx("option", { value: "", children: resolvedPaymentAccounts.length === 0 ? "No accounts configured yet" : "None (no bank details on invoice)" }),
              resolvedPaymentAccounts.map((acct) => /* @__PURE__ */ jsxs("option", { value: acct.id, children: [
                acct.label,
                " — ",
                acct.bankName,
                " (",
                acct.currency || "LKR",
                ")"
              ] }, acct.id))
            ]
          }),
          resolvedPaymentAccounts.length === 0 ? /* @__PURE__ */ jsx("p", { className: "text-[11px] text-amber-700 mt-1.5", children: "Add bank accounts under Admin → Settings → Invoice payment accounts, then refresh this page." }) : null
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsxs("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1 flex items-center gap-1", children: [
            /* @__PURE__ */ jsx(Link2, { size: 12 }),
            " Reference link (optional)"
          ] }),
          /* @__PURE__ */ jsx("input", {
            type: "url",
            className: "w-full px-3 py-2 text-sm bg-white border border-gray-200 rounded-md outline-none focus:border-indigo-500",
            placeholder: "https://…",
            value: newAttachmentLink,
            onChange: (e) => setNewAttachmentLink(e.target.value)
          })
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2", children: [
          /* @__PURE__ */ jsx("label", { className: "text-xs font-semibold text-slate-500 uppercase block mb-1", children: "Attachment for student (optional)" }),
          /* @__PURE__ */ jsxs("label", { className: "border-2 border-dashed border-gray-200 rounded-xl p-4 text-center hover:bg-slate-50 cursor-pointer transition-colors block", children: [
            /* @__PURE__ */ jsx("input", { type: "file", accept: ".jpg,.jpeg,.png,.pdf,.doc,.docx", className: "hidden", onChange: (event) => setNewAttachmentFile(event.target.files?.[0] || null) }),
            /* @__PURE__ */ jsx(Upload, { className: "mx-auto text-slate-400 mb-2", size: 22 }),
            /* @__PURE__ */ jsx("p", { className: "text-sm font-medium text-slate-600", children: newAttachmentFile ? newAttachmentFile.name : "Upload image, PDF, or document" }),
            /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-400 mt-1", children: `Sent with the invoice via WhatsApp when possible (max ${MAX_UPLOAD_LABEL})` })
          ] })
        ] }),
        /* @__PURE__ */ jsxs("div", { className: "md:col-span-2 flex gap-3 pt-2", children: [
          /* @__PURE__ */ jsx(Button, { type: "button", variant: "ghost", className: "flex-1", onClick: () => {
            setIsCreateOpen(false);
            resetCreateForm();
          }, children: "Cancel" }),
          /* @__PURE__ */ jsx(Button, { type: "submit", className: "flex-1", isLoading: isCreatingInvoice, children: "Issue Invoice" })
        ] })
      ] })
    ] }) }),
    /* @__PURE__ */ jsx("div", { className: "bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm", children: /* @__PURE__ */ jsxs("table", { className: "w-full text-sm text-left", children: [
      /* @__PURE__ */ jsx("thead", { className: "bg-gray-50 border-b border-gray-200 text-slate-500 font-medium", children: /* @__PURE__ */ jsxs("tr", { children: [
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4", children: "Description" }),
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4", children: "Amount" }),
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4", children: "Status" }),
        /* @__PURE__ */ jsx("th", { className: "px-6 py-4 text-right", children: "Action" })
      ] }) }),
      /* @__PURE__ */ jsx("tbody", { className: "divide-y divide-gray-100", children: invoicesLoading ? /* @__PURE__ */ jsx("tr", { children: /* @__PURE__ */ jsx("td", { colSpan: 4, className: "text-center py-8 text-slate-400", children: "Loading…" }) }) : studentInvoices.length === 0 ? /* @__PURE__ */ jsx("tr", { children: /* @__PURE__ */ jsx("td", { colSpan: 4, className: "text-center py-8 text-slate-400", children: "No invoices found." }) }) : studentInvoices.map((inv) => /* @__PURE__ */ jsxs("tr", { className: "hover:bg-slate-50 transition-colors cursor-pointer", onClick: () => handleOpenDetails(inv), children: [
        /* @__PURE__ */ jsxs("td", { className: "px-6 py-4 font-medium text-slate-700", children: [
          inv.description,
          !isStudentView && inv.createdByName ? /* @__PURE__ */ jsxs("div", { className: "text-xs text-slate-500 mt-0.5", children: [
            "Created by: ",
            inv.createdByName
          ] }) : null,
          isStudentView && invoiceHasDeliveryDetails(inv) ? /* @__PURE__ */ jsx("div", { className: "text-xs text-indigo-600 mt-0.5", children: "Payment details available" }) : null,
          inv.issueDate ? /* @__PURE__ */ jsxs("div", { className: "text-xs text-slate-400 mt-0.5", children: [
            "Issued: ",
            inv.issueDate
          ] }) : null
        ] }),
        /* @__PURE__ */ jsx("td", { className: "px-6 py-4 font-mono font-bold text-slate-900", children: /* @__PURE__ */ jsxs("div", { className: "flex flex-col", children: [
          /* @__PURE__ */ jsxs("span", { children: [
            inv.currency,
            " ",
            inv.amount.toLocaleString()
          ] }),
          inv.currency !== "LKR" && /* @__PURE__ */ jsxs("span", { className: "text-[10px] text-slate-400 font-normal", children: [
            "\u2248 ",
            formatLKR(inv.amount, inv.currency, exchangeRates)
          ] })
        ] }) }),
        /* @__PURE__ */ jsx("td", { className: "px-6 py-4", children: /* @__PURE__ */ jsx("span", { className: `inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-bold border ${getStatusColor(inv.status)}`, children: inv.status }) }),
        /* @__PURE__ */ jsx("td", { className: "px-6 py-4 text-right", children: /* @__PURE__ */ jsx(Button, { size: "sm", variant: "outline", onClick: (event) => {
          event.stopPropagation();
          handleOpenDetails(inv);
        }, children: "View More" }) })
      ] }, inv.id)) })
    ] }) }),
    isDetailsModalOpen && detailsInvoice && /* @__PURE__ */ jsx("div", { className: "fixed inset-0 z-50 overflow-y-auto overscroll-contain flex items-start justify-center py-8 px-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in", children: /* @__PURE__ */ jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-2xl p-6 w-full max-w-lg scale-100 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto my-auto", children: [
      /* @__PURE__ */ jsxs("div", { className: "flex justify-between items-center mb-4", children: [
        /* @__PURE__ */ jsx("h3", { className: "font-bold text-lg text-slate-900", children: "Invoice Details" }),
        /* @__PURE__ */ jsxs("button", { onClick: () => setIsDetailsModalOpen(false), className: "text-slate-400 hover:text-slate-600", children: [
          /* @__PURE__ */ jsx("span", { className: "sr-only", children: "Close" }),
          /* @__PURE__ */ jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: /* @__PURE__ */ jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" }) })
        ] })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "space-y-3 text-sm", children: [
        renderInvoiceDeliveryPanel(detailsInvoice),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Invoice ID: " }),
          /* @__PURE__ */ jsx("span", { className: "font-mono text-slate-800", children: detailsInvoice.id })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Description: " }),
          /* @__PURE__ */ jsx("span", { className: "font-semibold text-slate-800", children: detailsInvoice.description })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Amount: " }),
          /* @__PURE__ */ jsxs("span", { className: "font-semibold text-slate-800", children: [
            detailsInvoice.currency,
            " ",
            detailsInvoice.amount.toLocaleString()
          ] })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Status: " }),
          /* @__PURE__ */ jsx("span", { className: "font-semibold text-slate-800", children: detailsInvoice.status })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Issue Date: " }),
          /* @__PURE__ */ jsx("span", { className: "text-slate-800", children: detailsInvoice.issueDate || "-" })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: "Due Date: " }),
          /* @__PURE__ */ jsx("span", { className: "text-slate-800", children: detailsInvoice.dueDate || "-" })
        ] }),
        /* @__PURE__ */ jsxs("p", { children: [
          /* @__PURE__ */ jsx("span", { className: "text-slate-500", children: isStudentView ? "Your payment receipt: " : "Payment evidence: " }),
          detailsInvoice.paymentProofUrl ? /* @__PURE__ */ jsx("a", { href: detailsInvoice.paymentProofUrl, target: "_blank", rel: "noopener noreferrer", className: "text-indigo-600 font-semibold hover:underline", children: detailsInvoice.paymentProofName || "View evidence" }) : /* @__PURE__ */ jsx("span", { className: "text-slate-400", children: "Not uploaded" })
        ] })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "flex gap-3 mt-6 flex-wrap", children: [
        isStudentView && (detailsInvoice.status === "Pending" || detailsInvoice.status === "Overdue") ? /* @__PURE__ */ jsx(Button, { className: "flex-1 min-w-[140px]", onClick: () => {
          setIsDetailsModalOpen(false);
          handlePayClick(detailsInvoice);
        }, children: "Pay / upload receipt" }) : null,
        detailsInvoice.paymentProofUrl ? /* @__PURE__ */ jsx("a", { href: detailsInvoice.paymentProofUrl, target: "_blank", rel: "noopener noreferrer", className: "flex-1 min-w-[140px]", children: /* @__PURE__ */ jsx(Button, { variant: "outline", className: "w-full", children: isStudentView ? "View my receipt" : "View Evidence" }) }) : null,
        !isStudentView && canUploadEvidence && (detailsInvoice.status === "Pending" || detailsInvoice.status === "Overdue") ? /* @__PURE__ */ jsx(Button, { className: "flex-1", onClick: () => {
          setIsDetailsModalOpen(false);
          handlePayClick(detailsInvoice);
        }, children: "Upload Evidence" }) : null,
        canAcceptPayment && detailsInvoice.status === "Verifying" ? /* @__PURE__ */ jsxs(Fragment, { children: [
          /* @__PURE__ */ jsx(Button, { className: "flex-1", onClick: async () => {
            await handleApprove(detailsInvoice);
            setIsDetailsModalOpen(false);
          }, children: "Accept Payment" }),
          /* @__PURE__ */ jsx(Button, { variant: "outline", className: "flex-1 border-rose-200 text-rose-700 hover:bg-rose-50", onClick: () => setRejectModal({ open: true, invoice: detailsInvoice, reason: "", error: "" }), children: "Reject Evidence" })
        ] }) : null,
        /* @__PURE__ */ jsx(Button, { variant: "ghost", className: "flex-1", onClick: () => setIsDetailsModalOpen(false), children: "Close" })
      ] })
    ] }) }),
    isPaymentModalOpen && selectedInvoice && /* @__PURE__ */ jsx("div", { className: "fixed inset-0 z-50 overflow-y-auto overscroll-contain flex items-start justify-center py-8 px-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in", children: /* @__PURE__ */ jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-2xl p-6 w-full max-w-md scale-100 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto my-auto", children: [
      /* @__PURE__ */ jsxs("div", { className: "flex justify-between items-center mb-6", children: [
        /* @__PURE__ */ jsx("h3", { className: "font-bold text-lg text-slate-900", children: "Process Payment" }),
        /* @__PURE__ */ jsxs("button", { onClick: () => setIsPaymentModalOpen(false), className: "text-slate-400 hover:text-slate-600", children: [
          /* @__PURE__ */ jsx("span", { className: "sr-only", children: "Close" }),
          /* @__PURE__ */ jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: /* @__PURE__ */ jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" }) })
        ] })
      ] }),
      /* @__PURE__ */ jsxs("div", { className: "mb-6 bg-slate-50 p-4 rounded-lg border border-slate-100", children: [
        /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500 uppercase font-bold mb-1", children: "Total Amount" }),
        /* @__PURE__ */ jsxs("p", { className: "text-2xl font-bold text-slate-900", children: [
          selectedInvoice.currency,
          " ",
          selectedInvoice.amount.toLocaleString()
        ] }),
        selectedInvoice.currency !== "LKR" && /* @__PURE__ */ jsxs("p", { className: "text-xs text-slate-400 mt-1", children: [
          "\u2248 ",
          formatLKR(selectedInvoice.amount, selectedInvoice.currency, exchangeRates)
        ] }),
        /* @__PURE__ */ jsx("p", { className: "text-sm text-slate-600 mt-2", children: selectedInvoice.description })
      ] }),
      renderInvoiceDeliveryPanel(selectedInvoice),
      /* @__PURE__ */ jsxs("div", { className: "space-y-4 mb-6", children: [
        !canUploadEvidence && /* @__PURE__ */ jsxs("label", { className: `flex items-center p-4 border rounded-xl cursor-pointer transition-all ${paymentMethod === "card" ? "border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500" : "border-gray-200 hover:border-gray-300"}`, children: [
          /* @__PURE__ */ jsx("input", { type: "radio", name: "payment", className: "sr-only", checked: paymentMethod === "card", onChange: () => setPaymentMethod("card") }),
          /* @__PURE__ */ jsx("div", { className: `w-5 h-5 rounded-full border mr-3 flex items-center justify-center ${paymentMethod === "card" ? "border-indigo-600" : "border-gray-300"}`, children: paymentMethod === "card" && /* @__PURE__ */ jsx("div", { className: "w-2.5 h-2.5 bg-indigo-600 rounded-full" }) }),
          /* @__PURE__ */ jsxs("div", { children: [
            /* @__PURE__ */ jsx("p", { className: "font-semibold text-slate-900", children: "Pay by Card" }),
            /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500", children: "Secure checkout via Stripe" })
          ] })
        ] }),
        /* @__PURE__ */ jsxs("label", { className: `flex items-center p-4 border rounded-xl cursor-pointer transition-all ${paymentMethod === "upload" ? "border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500" : "border-gray-200 hover:border-gray-300"}`, children: [
          /* @__PURE__ */ jsx("input", { type: "radio", name: "payment", className: "sr-only", checked: paymentMethod === "upload", onChange: () => setPaymentMethod("upload") }),
          /* @__PURE__ */ jsx("div", { className: `w-5 h-5 rounded-full border mr-3 flex items-center justify-center ${paymentMethod === "upload" ? "border-indigo-600" : "border-gray-300"}`, children: paymentMethod === "upload" && /* @__PURE__ */ jsx("div", { className: "w-2.5 h-2.5 bg-indigo-600 rounded-full" }) }),
          /* @__PURE__ */ jsxs("div", { children: [
            /* @__PURE__ */ jsx("p", { className: "font-semibold text-slate-900", children: "Bank Transfer" }),
            /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-500", children: "Upload receipt/slip manually" })
          ] })
        ] })
      ] }),
      paymentMethod === "upload" && /* @__PURE__ */ jsxs("label", { className: "mb-6 border-2 border-dashed border-gray-200 rounded-xl p-6 text-center hover:bg-slate-50 cursor-pointer transition-colors block", children: [
        /* @__PURE__ */ jsx("input", { type: "file", accept: ".jpg,.jpeg,.png,.pdf,.doc,.docx", className: "hidden", onChange: (event) => setPaymentProofFile(event.target.files?.[0] || null) }),
        /* @__PURE__ */ jsx(Upload, { className: "mx-auto text-slate-400 mb-2", size: 24 }),
        /* @__PURE__ */ jsx("p", { className: "text-sm font-medium text-slate-600", children: paymentProofFile ? paymentProofFile.name : "Click to upload receipt" }),
        /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-400 mt-1", children: `PDF, JPG, PNG, DOC, or DOCX (max ${MAX_UPLOAD_LABEL})` })
      ] }),
      paymentError ? /* @__PURE__ */ jsx("p", { className: "text-xs text-rose-600 mb-4", children: paymentError }) : null,
      /* @__PURE__ */ jsxs("div", { className: "flex gap-3", children: [
        /* @__PURE__ */ jsx(Button, { variant: "ghost", className: "flex-1", onClick: () => setIsPaymentModalOpen(false), children: "Cancel" }),
        /* @__PURE__ */ jsx(Button, { className: "flex-1 bg-indigo-600 hover:bg-indigo-700 text-white", onClick: handlePaymentSubmit, isLoading: isSubmittingPayment, children: paymentMethod === "card" ? "Pay Now" : "Submit Receipt" })
      ] })
    ] }) }),
    rejectModal.open && rejectModal.invoice && /* @__PURE__ */ jsx("div", { className: "fixed inset-0 z-[60] overflow-y-auto overscroll-contain flex items-start justify-center py-8 px-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in", children: /* @__PURE__ */ jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-2xl p-6 w-full max-w-md scale-100 animate-in zoom-in-95 max-h-[90vh] overflow-y-auto my-auto", children: [
      /* @__PURE__ */ jsx("h3", { className: "font-bold text-lg text-slate-900 mb-2", children: "Reject payment evidence" }),
      /* @__PURE__ */ jsxs("p", { className: "text-sm text-slate-600 mb-4", children: [
        "Invoice ",
        rejectModal.invoice.id,
        " — provide a reason for the student."
      ] }),
      /* @__PURE__ */ jsx("textarea", { className: "w-full min-h-[100px] border border-gray-200 rounded-lg p-3 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500", placeholder: "Rejection reason...", value: rejectModal.reason, onChange: (event) => setRejectModal((prev) => ({ ...prev, reason: event.target.value, error: "" })) }),
      rejectModal.error ? /* @__PURE__ */ jsx("p", { className: "text-xs text-rose-600 mt-2", children: rejectModal.error }) : null,
      /* @__PURE__ */ jsxs("div", { className: "flex gap-3 mt-6", children: [
        /* @__PURE__ */ jsx(Button, { variant: "ghost", className: "flex-1", onClick: () => setRejectModal({ open: false, invoice: null, reason: "", error: "" }), children: "Cancel" }),
        /* @__PURE__ */ jsx(Button, { className: "flex-1 bg-rose-600 hover:bg-rose-700 text-white", onClick: handleReject, isLoading: isRejecting, children: "Reject Evidence" })
      ] })
    ] }) }),
    whatsappNotification.show && /* @__PURE__ */ jsx("div", { className: "fixed bottom-6 right-6 z-50 animate-in slide-in-from-bottom-5 fade-in duration-300", children: /* @__PURE__ */ jsxs("div", { className: "bg-white border border-emerald-100 shadow-xl rounded-lg p-4 flex items-start gap-3 max-w-sm", children: [
      /* @__PURE__ */ jsx("div", { className: "p-2 bg-emerald-50 rounded-full text-emerald-600", children: /* @__PURE__ */ jsx(MessageCircle, { size: 18 }) }),
      /* @__PURE__ */ jsxs("div", { className: "flex-1", children: [
        /* @__PURE__ */ jsx("p", { className: "text-sm font-bold text-slate-900", children: "WhatsApp Sent" }),
        /* @__PURE__ */ jsx("p", { className: "text-xs text-slate-600 mt-1 leading-relaxed", children: whatsappNotification.message })
      ] }),
      /* @__PURE__ */ jsx("button", { onClick: () => setWhatsappNotification({ show: false, message: "" }), className: "text-slate-400 hover:text-slate-600", children: /* @__PURE__ */ jsx(X, { size: 16 }) })
    ] }) })
  ] });
};
export {
  FinanceModule
};
