export {
  COMPANY_NAME,
  COMPANY_SHORT_NAME,
  PRODUCT_TAGLINE,
  APP_TITLE,
  COMPANY_AI_BRAND,
  COMPANY_LOGO_ALT,
  RESUME_BUILDER_TITLE,
  COMPANY_FULL_LOGO,
  ACTIVE_PROFILE,
  applyCompanyBrandingToDocument,
} from "./profileConfig";
